/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upb.chatupb_v2.view;

import edu.upb.chatupb_v2.controller.ChatsController;
import edu.upb.chatupb_v2.controller.ContactController;
import edu.upb.chatupb_v2.model.entities.message.*;
import edu.upb.chatupb_v2.controller.Mediador;
import lombok.Setter;

import javax.swing.*;
import javax.swing.text.DefaultEditorKit;
import java.awt.*;
import java.awt.event.*;
import java.util.List;

public class ChatUI extends JFrame implements iChatView {
    public String idUsuarioActual;
    private DefaultListModel<Contact> contacModel = new DefaultListModel<>();
    private ChatUIStyles styles;
    @Setter
    public ContactController contactController;
    @Setter
    public ChatsController chatsController;

    public ChatUI() {
        styles = new ChatUIStyles();
        initComponents();
        this.jContactos.setCellRenderer(new ContactRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

// </editor-fold>//GEN-END:initComponents
    private void initComponents() {
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }

        jtMensaje = new JTextField();
        jPanelChat = new JPanel();
        jPanelChat.setLayout(new BoxLayout(jPanelChat, BoxLayout.Y_AXIS));
        jPanelChat.setBackground(styles.getBgPanel());

        jScrollPaneChat = new JScrollPane(jPanelChat);
        jScrollPaneChat.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        jScrollPaneChat.setBackground(styles.getBgSidebar());
        jScrollPaneChat.getVerticalScrollBar().setBackground(styles.getBgSidebar());
        jScrollPaneChat.setBorder(null);
        jScrollPaneChat.getViewport().setBackground(styles.getBgPanel());
        styles.styleScrollBar(jScrollPaneChat);

        jContactos = new JList<>();
        jPopupMenu = new JPopupMenu();
        styles.stylePopupMenu(jPopupMenu);

        itemHello = styles.createMenuItem("Enviar hello");
        itemZumbido = styles.createMenuItem("Enviar Zumbido");
        itemInvitacion = styles.createMenuItem("Enviar invitacion");
        itemEnviarContacto = styles.createMenuItem("Enviar contacto");
        itemActualizarIp = styles.createMenuItem("Actualizar Ip");
        jPopupMenu.add(itemHello);
        jPopupMenu.add(itemZumbido);
        jPopupMenu.add(itemInvitacion);
        jPopupMenu.add(itemEnviarContacto);
        jPopupMenu.add(itemActualizarIp);

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setSize(900, 600);
        setLocationRelativeTo(null);
        setBackground(styles.getBgDark());

        jBtnEnviar = styles.createSendButton();
        jBtnEnviar.addActionListener(evt -> jBtnEnviarActionPerformed(evt));

        jBtnNuevaConexion = styles.createNuevaConexionButton("+", "Agregar contacto");
        jBtnNuevaConexion.addActionListener(evt -> jBtnNuevaConexionActionPerformed(evt));

        jBtnOff = styles.createOffButton("⏻");
        jBtnOff.addActionListener(evt -> jBtnOffActionPerformed(evt));

        jBtnTheme = styles.createThemeButton();
        jBtnTheme.addActionListener(e -> showThemeSelector());

        setLayout(new BorderLayout());
        getContentPane().setBackground(styles.getBgDark());

        // ── Panel contactos (sidebar) ───────────────────────────────────
        panelContactos = new JPanel(new BorderLayout());
        panelContactos.setPreferredSize(new Dimension(240, 0));
        panelContactos.setBackground(styles.getBgSidebar());
        panelContactos.setBorder(BorderFactory.createMatteBorder(
                0, 0, 0, 1, new Color(255, 255, 255, 18)));

        sidebarHeader = new JPanel(new BorderLayout());
        sidebarHeader.setBackground(styles.getBgSidebar());
        sidebarHeader.setBorder(BorderFactory.createEmptyBorder(14, 12, 10, 12));

        jtBuscadorContactos = styles.createSearchField();
        jtBuscadorContactos.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { filtrarContactos(); }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { filtrarContactos(); }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { filtrarContactos(); }
        });
        jtBuscadorContactos.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) { jtBuscadorContactos.repaint(); }
            @Override
            public void focusLost(FocusEvent e) { jtBuscadorContactos.repaint(); }
        });

        sidebarHeader.add(jtBuscadorContactos, BorderLayout.CENTER);
        sidebarHeader.add(styles.buildSidebarDivider(), BorderLayout.SOUTH);

        lblContactoSeleccionado = new JLabel("ChatUPB");
        jContactos = new JList<>(contacModel);
        jContactos.setCellRenderer(new ContactRenderer());
        jContactos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jContactos.setFixedCellHeight(58);
        jContactos.setBackground(styles.getBgSidebar());
        jContactos.setBorder(BorderFactory.createEmptyBorder(4, 0, 4, 0));
        jContactos.setSelectionBackground(new Color(79, 70, 229, 60));
        jContactos.setSelectionForeground(styles.getTextPrimary());

        // ── Listeners de contactos ──────────────────────────────────────
        jContactos.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                Contact seleccionado = jContactos.getSelectedValue();
                if (seleccionado != null && chatsController != null) {
                    lblContactoSeleccionado.setText(seleccionado.getName());
                    seleccionado.setMensajesNoLeidos(false);
                    seleccionado.setZumbido(false);
                    jContactos.repaint();
                    idUsuarioActual = seleccionado.getId();
                    limpiarChat();
                    chatsController.onloadMessages(Mediador.ID_MIO, idUsuarioActual);
                }
            }
        });
        jContactos.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseMoved(MouseEvent e) {
                int index = jContactos.locationToIndex(e.getPoint());
                if (index != -1) {
                    Rectangle cellBounds = jContactos.getCellBounds(index, index);
                    if (cellBounds != null && cellBounds.contains(e.getPoint())) {
                        ((ContactRenderer) jContactos.getCellRenderer()).setHoverIndex(index);
                    } else {
                        ((ContactRenderer) jContactos.getCellRenderer()).setHoverIndex(-1);
                    }
                } else {
                    ((ContactRenderer) jContactos.getCellRenderer()).setHoverIndex(-1);
                }
                jContactos.repaint();
            }
        });
        jContactos.addMouseListener(new MouseAdapter() {
            private void mostrarMenu(MouseEvent e) {
                if (SwingUtilities.isRightMouseButton(e)) {
                    int pos = jContactos.locationToIndex(e.getPoint());
                    if (pos != -1) {
                        Rectangle cellBounds = jContactos.getCellBounds(pos, pos);
                        if (cellBounds != null && cellBounds.contains(e.getPoint())) {
                            jContactos.setSelectedIndex(pos);
                            jPopupMenu.show(jContactos, e.getX(), e.getY());
                        }
                    }
                }
            }
            @Override
            public void mousePressed(MouseEvent e) {
                int index = jContactos.locationToIndex(e.getPoint());
                if (index != -1) {
                    Rectangle cellBounds = jContactos.getCellBounds(index, index);
                    if (cellBounds == null || !cellBounds.contains(e.getPoint())) {
                        jContactos.clearSelection();
                        limpiarChat();
                        idUsuarioActual = " ";
                        lblContactoSeleccionado.setText("ChatUPB");
                    }
                }
                mostrarMenu(e);
            }
            @Override
            public void mouseReleased(MouseEvent e) {
                mostrarMenu(e);
            }
            @Override
            public void mouseExited(MouseEvent e) {
                ((ContactRenderer) jContactos.getCellRenderer()).setHoverIndex(-1);
                jContactos.repaint();
            }
        });

        // ── Acciones del popup de contactos ─────────────────────────────
        itemHello.addActionListener(e -> {
            Contact seleccionado = jContactos.getSelectedValue();
            if (seleccionado != null && chatsController != null) {
                idUsuarioActual = seleccionado.getId();
                Mediador.getInstance().enviarHello(idUsuarioActual);
            }
        });
        itemZumbido.addActionListener(e -> {
            Contact seleccionado = jContactos.getSelectedValue();
            if (seleccionado != null) {
                idUsuarioActual = seleccionado.getId();
                Zumbido zumbido = new Zumbido(Mediador.ID_MIO);
                Mediador.getInstance().sendMessage(idUsuarioActual, zumbido);
            }
        });
        itemEnviarContacto.addActionListener(e -> showEnviarContactoPopup());
        itemInvitacion.addActionListener(e -> {
            Contact seleccionado = jContactos.getSelectedValue();
            if (seleccionado != null) {
                idUsuarioActual = seleccionado.getId();
                Mediador.getInstance().establecerConexion(seleccionado.getIp());
            }
        });
        itemActualizarIp.addActionListener(e -> {
            Contact seleccionado = jContactos.getSelectedValue();
            if (seleccionado != null) {
                idUsuarioActual = seleccionado.getId();
                showIpPopup();
            }
        });

        scrollContactos = new JScrollPane(jContactos);
        scrollContactos.setBorder(null);
        scrollContactos.getViewport().setBackground(styles.getBgSidebar());
        scrollContactos.setBackground(styles.getBgSidebar());
        scrollContactos.getVerticalScrollBar().setBackground(styles.getBgSidebar());
        styles.styleScrollBar(scrollContactos);

        panelContactos.add(sidebarHeader, BorderLayout.NORTH);
        panelContactos.add(scrollContactos, BorderLayout.CENTER);

        // ── Panel chat (derecho) ────────────────────────────────────────
        panelChat = new JPanel(new BorderLayout());
        panelChat.setBackground(styles.getBgPanel());

        panelSuperior = new JPanel(new BorderLayout());
        panelSuperior.setBackground(styles.getBgSidebar());
        panelSuperior.setBorder(BorderFactory.createEmptyBorder(12, 20, 12, 16));

        lblContactoSeleccionado.setFont(new Font("Tahoma", Font.BOLD, 15));
        lblContactoSeleccionado.setForeground(styles.getAccent());
        panelSuperior.add(lblContactoSeleccionado, BorderLayout.WEST);

        JPanel botonesHeader = new JPanel(new FlowLayout(FlowLayout.RIGHT, 8, 0));
        botonesHeader.setOpaque(false);
        botonesHeader.add(jBtnTheme);
        botonesHeader.add(jBtnOff);
        botonesHeader.add(jBtnNuevaConexion);
        panelSuperior.add(botonesHeader, BorderLayout.EAST);

        JSeparator sep = new JSeparator();
        sep.setForeground(styles.getDivider());
        sep.setBackground(styles.getBgSidebar());
        panelSuperior.add(sep, BorderLayout.SOUTH);

        JPanel panelInferior = buildInputPanel();

        panelChat.add(panelSuperior, BorderLayout.NORTH);
        panelChat.add(jScrollPaneChat, BorderLayout.CENTER);
        panelChat.add(panelInferior, BorderLayout.SOUTH);

        add(panelContactos, BorderLayout.WEST);
        add(panelChat, BorderLayout.CENTER);

        // ── Panel mensaje fijado ────────────────────────────────────────
        panelMensajeFijado = new JPanel(new BorderLayout());
        panelMensajeFijado.setBackground(new Color(45, 38, 90));
        panelMensajeFijado.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(79, 70, 229, 80)),
                BorderFactory.createEmptyBorder(7, 16, 7, 16)
        ));
        panelMensajeFijado.setVisible(false);

        JLabel iconPin = new JLabel("📌");
        iconPin.setFont(new Font("Segoe UI Emoji", Font.PLAIN, 13));
        iconPin.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 8));

        lblMensajeFijado = new JLabel("Mensaje fijado");
        lblMensajeFijado.setForeground(styles.getAccent());
        lblMensajeFijado.setFont(new Font("Tahoma", Font.PLAIN, 12));

        JButton btnDesfijar = new JButton("✕");
        btnDesfijar.setFont(new Font("Tahoma", Font.PLAIN, 11));
        btnDesfijar.setForeground(styles.getTextMuted());
        btnDesfijar.setContentAreaFilled(false);
        btnDesfijar.setBorderPainted(false);
        btnDesfijar.setFocusPainted(false);
        btnDesfijar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnDesfijar.addActionListener(e -> desfijarMensaje());

        JPanel pinLeft = new JPanel(new FlowLayout(FlowLayout.LEFT, 0, 0));
        pinLeft.setOpaque(false);
        pinLeft.add(iconPin);
        pinLeft.add(lblMensajeFijado);
        panelMensajeFijado.add(pinLeft, BorderLayout.WEST);
        panelMensajeFijado.add(btnDesfijar, BorderLayout.EAST);

        JPanel panelNorte = new JPanel(new BorderLayout());
        panelNorte.add(panelSuperior, BorderLayout.NORTH);
        panelNorte.add(panelMensajeFijado, BorderLayout.SOUTH);
        panelChat.add(panelNorte, BorderLayout.NORTH);
        panelChat.add(jScrollPaneChat, BorderLayout.CENTER);
        panelChat.add(panelInferior, BorderLayout.SOUTH);

        if (Mediador.getInstance().dbVacia()) {
            showNombrePopup();
        }
        Mediador.getInstance().cargarMisDatos();
    }

    private JPanel buildInputPanel() {
        panelInferior = new JPanel(new BorderLayout(10, 0));
        panelInferior.setBackground(styles.getBgSidebar());
        panelInferior.setBorder(BorderFactory.createEmptyBorder(14, 16, 14, 16));

        jtMensaje = styles.createMessageField();
        jtMensaje.addActionListener(evt -> jBtnEnviarActionPerformed(evt));

        JPanel panelBotones = new JPanel(new FlowLayout(FlowLayout.RIGHT, 6, 0));
        panelBotones.setOpaque(false);

        jBtnMensajeUnico = styles.createMensajeUnicoButton();
        jBtnMensajeUnico.addActionListener(evt -> {
            modoMensajeUnico = !modoMensajeUnico;
            jBtnMensajeUnico.setForeground(modoMensajeUnico ? styles.getBtnUnicoActive() : styles.getAccent());
            jBtnMensajeUnico.setToolTipText(modoMensajeUnico ?
                    "Mensaje único ACTIVADO (clic para desactivar)" :
                    "Mensaje único (se ve solo una vez)");
            jBtnMensajeUnico.repaint();
        });

        panelBotones.add(jBtnMensajeUnico);
        panelBotones.add(jBtnEnviar);
        panelInferior.add(jtMensaje, BorderLayout.CENTER);
        panelInferior.add(panelBotones, BorderLayout.EAST);

        jtMensaje.getInputMap(JComponent.WHEN_FOCUSED).put(
                KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.Toolkit.getDefaultToolkit().getMenuShortcutKeyMaskEx()),
                DefaultEditorKit.pasteAction
        );
        jtMensaje.getInputMap(JComponent.WHEN_FOCUSED).put(
                KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.Toolkit.getDefaultToolkit().getMenuShortcutKeyMaskEx()),
                DefaultEditorKit.copyAction
        );
        jtMensaje.getInputMap(JComponent.WHEN_FOCUSED).put(
                KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.Toolkit.getDefaultToolkit().getMenuShortcutKeyMaskEx()),
                DefaultEditorKit.cutAction
        );
        jtMensaje.getInputMap(JComponent.WHEN_FOCUSED).put(
                KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.Toolkit.getDefaultToolkit().getMenuShortcutKeyMaskEx()),
                DefaultEditorKit.selectAllAction
        );
        return panelInferior;
    }
    public void showThemeSelector() {
        JPopupMenu popupTema = new JPopupMenu();
        styles.stylePopupMenu(popupTema);

        String[][] temas = {
                {"1", "UNO"}, {"2", "DOS"}, {"3", "CUATRO"}, {"4", "TRES"}, {"5", "CINCO"}
        };
        for (String[] t : temas) {
            JMenuItem item = styles.createMenuItem(t[0]);
            item.addActionListener(e -> {
                ThemeManager.setTheme(ThemeManager.Theme.valueOf(t[1]));
                aplicarTema();
                CambiarTema cambiarTema = new CambiarTema(Mediador.ID_MIO, t[0]);
                Mediador.getInstance().sendMessage(idUsuarioActual, cambiarTema);
            });
            popupTema.add(item);
        }
        popupTema.show(jBtnTheme, 0, jBtnTheme.getHeight());
    }
    private void aplicarTema() {
        styles.aplicarTemaComponentes(
                this, jPanelChat, jScrollPaneChat,
                jContactos, jtBuscadorContactos, jtMensaje,
                lblContactoSeleccionado, lblMensajeFijado,
                jBtnMensajeUnico, modoMensajeUnico,
                jBtnNuevaConexion, jBtnTheme,
                panelContactos, panelChat, panelSuperior,
                panelInferior, sidebarHeader,
                scrollContactos, panelMensajeFijado
        );
        if (idUsuarioActual != null && !idUsuarioActual.equals(" ") && chatsController != null) {
            chatsController.onloadMessages(Mediador.ID_MIO, idUsuarioActual);
        }
    }

    private void showOffPopup() {
        JDialog dialog = styles.createBaseDialog(this, 360, 240);
        JPanel root = new JPanel(null); root.setOpaque(false);
        JPanel card = styles.createDarkCard(20, 30, 320, 170);
        JLabel robot = styles.createRobotIcon(230, -20, "/images/robotOff.png", getClass());
        JLabel title = new JLabel("Conexión terminada");
        title.setFont(new Font("Georgia", Font.BOLD, 16));
        title.setForeground(styles.getTextPrimary());
        title.setBounds(20, 30, 200, 28);
        JLabel sub = new JLabel("Tu sesión fue cerrada.");
        sub.setFont(new Font("Tahoma", Font.PLAIN, 12));
        sub.setForeground(styles.getTextMuted());
        sub.setBounds(20, 62, 200, 20);
        JButton ok = styles.createPopupOkButton("Aceptar", 20, 110, 100, 34);
        ok.addActionListener(e -> dialog.dispose());
        card.add(title); card.add(sub); card.add(ok);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }
    private void showAcceptPopup() {
        JDialog dialog = styles.createBaseDialog(this, 340, 220);
        JPanel root = new JPanel(null); root.setOpaque(false);
        JPanel card = styles.createDarkCard(20, 30, 300, 160);
        JLabel robot = styles.createRobotIcon(210, -15, "/images/robotAccept.png", getClass());
        JLabel title = new JLabel("¡Conexión aceptada!");
        title.setFont(new Font("Georgia", Font.BOLD, 16));
        title.setForeground(styles.getTextPrimary());
        title.setBounds(20, 30, 200, 28);
        JButton ok = styles.createPopupOkButton("OK", 20, 100, 90, 34);
        ok.addActionListener(e -> dialog.dispose());
        card.add(title); card.add(ok);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }
    private void showDeclinePopup() {
        JDialog dialog = styles.createBaseDialog(this, 340, 220);
        JPanel root = new JPanel(null); root.setOpaque(false);
        JPanel card = styles.createDarkCard(20, 30, 300, 160);
        JLabel robot = styles.createRobotIcon(210, -15, "/images/robotDecline.png", getClass());
        JLabel title = new JLabel("Conexión rechazada");
        title.setFont(new Font("Georgia", Font.BOLD, 16));
        title.setForeground(styles.getTextPrimary());
        title.setBounds(20, 30, 200, 28);
        JButton ok = styles.createPopupOkButton("OK", 20, 100, 90, 34);
        ok.addActionListener(e -> dialog.dispose());
        card.add(title); card.add(ok);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }
    private void showHelloRechazadoPopup() {
        JDialog dialog = styles.createBaseDialog(this, 340, 220);
        JPanel root = new JPanel(null); root.setOpaque(false);
        JPanel card = styles.createDarkCard(20, 30, 300, 160);
        JLabel robot = styles.createRobotIcon(210, -15, "/images/robotDecline.png", getClass());
        JLabel title = new JLabel("Hello rechazado");
        title.setFont(new Font("Georgia", Font.BOLD, 16));
        title.setForeground(styles.getTextPrimary());
        title.setBounds(20, 30, 200, 28);
        JButton ok = styles.createPopupOkButton("OK", 20, 100, 90, 34);
        ok.addActionListener(e -> dialog.dispose());
        card.add(title); card.add(ok);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }
    private void showSeleccionarContactoPopup() {
        JDialog dialog = styles.createBaseDialog(this, 340, 220);
        JPanel root = new JPanel(null); root.setOpaque(false);
        JPanel card = styles.createDarkCard(20, 30, 300, 150);
        JLabel robot = styles.createRobotIcon(220, -15, "/images/contact.png", getClass());
        JLabel title = new JLabel("Seleccione un contacto");
        title.setFont(new Font("Georgia", Font.BOLD, 16));
        title.setForeground(styles.getTextPrimary());
        title.setBounds(20, 30, 200, 28);
        JButton ok = styles.createPopupOkButton("OK", 20, 90, 90, 34);
        ok.addActionListener(e -> dialog.dispose());
        card.add(title); card.add(ok);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }
    public boolean showInvitationPopup(String nombreContacto) {
        final boolean[] accepted = {false};
        JDialog dialog = styles.createBaseDialog(this, 400, 270);
        JPanel root = new JPanel(null); root.setOpaque(false);
        JPanel card = styles.createDarkCard(20, 40, 360, 200);
        JLabel robot = styles.createRobotIcon(260, -10, "/images/robotRequest.png", getClass());
        JLabel title = new JLabel("Invitación de conexión");
        title.setFont(new Font("Georgia", Font.BOLD, 16));
        title.setForeground(styles.getTextPrimary());
        title.setBounds(20, 20, 240, 28);
        JLabel sub = new JLabel("<html><body style='color:#94a3b8;font-size:12px;'>" + nombreContacto + " quiere conectarse</body></html>");
        sub.setBounds(20, 54, 240, 24);
        JButton accept = styles.createPopupOkButton("Aceptar", 20, 140, 110, 36);
        accept.addActionListener(e -> { accepted[0] = true; dialog.dispose(); });
        JButton decline = styles.createDeclineButton("Rechazar", 148, 140, 110, 36);
        decline.addActionListener(e -> { accepted[0] = false; dialog.dispose(); });
        card.add(title); card.add(sub); card.add(accept); card.add(decline);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
        return accepted[0];
    }
    public boolean showEliminarMensajePopup() {
        final boolean[] accepted = {false};
        JDialog dialog = styles.createBaseDialog(this, 400, 270);
        JPanel root = new JPanel(null); root.setOpaque(false);
        JPanel card = styles.createDarkCard(20, 40, 360, 150);
        JLabel robot = styles.createRobotIcon(285, -10, "/images/delete.png", getClass());
        JLabel title = new JLabel("<html><div style='text-align:left;'>¿Seguro que desea eliminar el mensaje?</div></html>");
        title.setFont(new Font("Georgia", Font.BOLD, 16));
        title.setForeground(styles.getTextPrimary());
        title.setBounds(20, 20, 310, 60);
        JButton accept = styles.createPopupOkButton("Si", 20, 90, 110, 36);
        accept.addActionListener(e -> { accepted[0] = true; dialog.dispose(); });
        JButton decline = styles.createDeclineButton("No", 148, 90, 110, 36);
        decline.addActionListener(e -> { accepted[0] = false; dialog.dispose(); });
        card.add(title); card.add(accept); card.add(decline);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
        return accepted[0];
    }
    private void showNuevaConexionPopup() {
        JDialog dialog = styles.createBaseDialog(this, 420, 310);
        JPanel root = new JPanel(null); root.setOpaque(false);
        JPanel card = styles.createDarkCard(20, 40, 380, 250);
        JLabel robot = styles.createRobotIcon(280, -10, "/images/robotAdd.png", getClass());
        JButton btnCerrar = styles.createCloseButton(getClass());
        btnCerrar.setBounds(340, 12, 25, 25);
        btnCerrar.addActionListener(e -> dialog.dispose());
        JLabel title = new JLabel("Agregar Contacto");
        title.setFont(new Font("Georgia", Font.BOLD, 18));
        title.setForeground(styles.getTextPrimary());
        title.setBounds(24, 24, 240, 30);
        JLabel lbl = new JLabel("IP del contacto:");
        lbl.setFont(new Font("Tahoma", Font.PLAIN, 12));
        lbl.setForeground(styles.getTextMuted());
        lbl.setBounds(24, 76, 200, 20);
        jtIp = styles.createDarkTextField(24, 100, 330, 40);
        jBtnConectar = styles.createPopupOkButton("Conectar", 24, 162, 140, 38);
        jBtnConectar.addActionListener(evt -> {
            Mediador.getInstance().establecerConexion(jtIp.getText());
            dialog.dispose();
        });
        card.add(btnCerrar); card.add(title); card.add(lbl); card.add(jtIp); card.add(jBtnConectar);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }
    public void showNombrePopup() {
        JDialog dialog = styles.createBaseDialog(this, 420, 310);
        JPanel root = new JPanel(null); root.setOpaque(false);
        JPanel card = styles.createDarkCard(20, 40, 380, 250);
        JLabel robot = styles.createRobotIcon(280, -10, "/images/robotAdd.png", getClass());
        JLabel title = new JLabel("¡Bienvenido!");
        title.setFont(new Font("Georgia", Font.BOLD, 20));
        title.setForeground(styles.getAccent());
        title.setBounds(24, 24, 200, 32);
        JLabel lbl = new JLabel("Tu nombre:");
        lbl.setFont(new Font("Tahoma", Font.PLAIN, 12));
        lbl.setForeground(styles.getTextMuted());
        lbl.setBounds(24, 76, 200, 20);
        jtName = styles.createDarkTextField(24, 100, 330, 40);
        jBtnAceptar = styles.createPopupOkButton("Comenzar →", 24, 162, 150, 38);
        jBtnAceptar.addActionListener(evt -> {
            Mediador.getInstance().primerRegistro(jtName.getText());
            dialog.dispose();
        });
        card.add(title); card.add(lbl); card.add(jtName); card.add(jBtnAceptar);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }
    public void showIpPopup() {
        JDialog dialog = styles.createBaseDialog(this, 420, 300);
        JPanel root = new JPanel(null); root.setOpaque(false);
        JPanel card = styles.createDarkCard(20, 40, 380, 240);
        JLabel robot = styles.createRobotIcon(260, -10, "/images/robotAdd.png", getClass());
        JButton btnCerrar = styles.createCloseButton(getClass());
        btnCerrar.setBounds(340, 12, 25, 25);
        btnCerrar.addActionListener(e -> dialog.dispose());
        JLabel title = new JLabel("Actualizar IP");
        title.setFont(new Font("Georgia", Font.BOLD, 18));
        title.setForeground(styles.getTextPrimary());
        title.setBounds(24, 24, 200, 30);
        JLabel lbl = new JLabel("Nueva IP:");
        lbl.setFont(new Font("Tahoma", Font.PLAIN, 12));
        lbl.setForeground(styles.getTextMuted());
        lbl.setBounds(24, 70, 200, 20);
        jtName = styles.createDarkTextField(24, 94, 330, 40);
        jBtnAceptar = styles.createPopupOkButton("Guardar", 24, 155, 120, 38);
        jBtnAceptar.addActionListener(evt -> {
            this.contactController.actualizarIp(idUsuarioActual, jtName.getText());
            dialog.dispose();
        });
        card.add(btnCerrar); card.add(title); card.add(lbl); card.add(jtName); card.add(jBtnAceptar);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }
    private void showEnviarContactoPopup() {
        JDialog dialog = styles.createBaseDialog(this, 420, 310);
        JPanel root = new JPanel(null); root.setOpaque(false);
        JPanel card = styles.createDarkCard(20, 40, 380, 250);
        JLabel robot = styles.createRobotIcon(280, -10, "/images/robotAdd.png", getClass());
        JButton btnCerrar = styles.createCloseButton(getClass());
        btnCerrar.setBounds(340, 12, 25, 25);
        btnCerrar.addActionListener(e -> dialog.dispose());
        JLabel title = new JLabel("Compartir Contacto");
        title.setFont(new Font("Georgia", Font.BOLD, 18));
        title.setForeground(styles.getTextPrimary());
        title.setBounds(24, 24, 240, 30);
        JLabel lbl = new JLabel("Nombre a compartir:");
        lbl.setFont(new Font("Tahoma", Font.PLAIN, 12));
        lbl.setForeground(styles.getTextMuted());
        lbl.setBounds(24, 76, 220, 20);
        jtNameEnviarContacto = styles.createDarkTextField(24, 100, 330, 40);
        jBtnEnviarContacto = styles.createPopupOkButton("Enviar →", 24, 162, 120, 38);
        jBtnEnviarContacto.addActionListener(evt -> {
            Mediador.getInstance().enviarContacto(idUsuarioActual, jtNameEnviarContacto.getText());
            dialog.dispose();
        });
        card.add(btnCerrar); card.add(title); card.add(lbl); card.add(jtNameEnviarContacto); card.add(jBtnEnviarContacto);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }
    private void showAgregarContactoPopup() {
        JDialog dialog = styles.createBaseDialog(this, 340, 210);
        JPanel root = new JPanel(null); root.setOpaque(false);
        JPanel card = styles.createDarkCard(20, 30, 300, 160);
        JLabel robot = styles.createRobotIcon(210, -10, "/images/robotAccept.png", getClass());
        JLabel title = new JLabel("✓ Contacto agregado");
        title.setFont(new Font("Georgia", Font.BOLD, 16));
        title.setForeground(new Color(134, 239, 172));
        title.setBounds(20, 28, 220, 28);
        JButton ok = styles.createPopupOkButton("OK", 20, 100, 90, 34);
        ok.addActionListener(e -> dialog.dispose());
        card.add(title); card.add(ok);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }
    public void showMensajeUnicoPopup(String mensaje) {
        JDialog dialog = styles.createBaseDialog(this, 400, 300);
        JPanel root = new JPanel(null);
        root.setOpaque(false);
        JPanel card = styles.createDarkCard(20, 40, 360, 230);
        JLabel robot = styles.createRobotIcon(260, -10, "/images/robotRequest.png", getClass());
        JLabel title = new JLabel("Mensaje Único");
        title.setFont(new Font("Georgia", Font.BOLD, 16));
        title.setForeground(styles.getTextPrimary());
        title.setBounds(20, 20, 240, 28);
        JTextArea textArea = styles.crearTextAreaMensajeUnico(mensaje);
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setBounds(20, 54, 320, 100);
        scrollPane.setBorder(null);
        scrollPane.getViewport().setBackground(new Color(30, 41, 59));
        styles.styleScrollBar(scrollPane);
        JButton ok = styles.createPopupOkButton("OK", 20, 170, 90, 34);
        ok.addActionListener(e -> dialog.dispose());
        card.add(title);
        card.add(scrollPane);
        card.add(ok);
        root.add(robot);
        root.add(card);
        dialog.add(root);
        dialog.setVisible(true);
    }

    private void jBtnEnviarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jBtnEnviarActionPerformed
        String mensajeTxt = jtMensaje.getText().toString();
        if (!mensajeTxt.isEmpty() && jContactos.getSelectedValue() == null) {
            showSeleccionarContactoPopup();
            return;
        }
        if (mensajeTxt.isEmpty() || idUsuarioActual == null || idUsuarioActual.equals(" ")) {
            return;
        }
        System.out.println("Enviando 007..."); Mediador.getInstance().enviarMensajePorChat(idUsuarioActual, mensajeTxt);
        jtMensaje.setText("");
        if (modoMensajeUnico) {
            modoMensajeUnico = false;
            jBtnMensajeUnico.setForeground(styles.getAccent());
            jBtnMensajeUnico.setToolTipText("Mensaje único (se ve solo una vez)");
            jBtnMensajeUnico.repaint();
        }
    }//GEN-LAST:event_jBtnEnviarActionPerformed
    private void jBtnOffActionPerformed(ActionEvent evt) {
        try {
            for (Contact c : todosLosContactos) {
                c.setStateConnect(false);
            }
            System.out.println("Enviando 0018...");System.out.println("Conexion terminada");
            Message message = new FueraLinea(Mediador.ID_MIO);
            Mediador.getInstance().enviarMensajeATodos(message);
            if (jContactos.getSelectedValue() != null)
                mostrarMensajeSistema("CONEXION TERMINADA");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void jBtnNuevaConexionActionPerformed(ActionEvent evt) {
        showNuevaConexionPopup();
    }

    public void agregarContacto(Contact contact) {
        if (contact == null || contact.getId() == null) {
            return;
        }
        for (int i = 0; i < contacModel.size(); i++) {
            if (contacModel.get(i).getId().equals(contact.getId())) {
                return;
            }
        }
        todosLosContactos.add(contact);
        String filtro = jtBuscadorContactos.getText().toLowerCase().trim();
        if (filtro.isEmpty() || (contact.getName() != null && contact.getName().toLowerCase().contains(filtro))) {
            contacModel.addElement(contact);
        }
    }
    public void actualizarContacto(Contact contact) {
        for (int i = 0; i < contacModel.size(); i++) {
            Contact c = contacModel.get(i);
            if (c.getId().equals(contact.getId())) {
                c.setName(contact.getName());
                c.setIp(contact.getIp());
                contacModel.set(i, c);
                break;
            }
        }
        jContactos.repaint();
    }
    public void actualizarEstadoContacto(String id, boolean estado) {
        for (int i = 0; i < contacModel.size(); i++) {
            Contact c = contacModel.get(i);
            if (c.getId().equals(id)) {
                c.setStateConnect(estado);
                contacModel.set(i, c);
                break;
            }
        }
        jContactos.repaint();
    }
    public void marcarContactoConMensajeNuevo(String id) {
        for (int i = 0; i < contacModel.size(); i++) {
            Contact c = contacModel.get(i);
            if (c.getId().equals(id)) {
                c.setMensajesNoLeidos(true);
                contacModel.set(i, c);
                break;
            }
        }
        jContactos.repaint();
    }
    public void marcarZumbido(String id) {
        for (int i = 0; i < contacModel.size(); i++) {
            Contact c = contacModel.get(i);
            if (c.getId().equals(id)) {
                c.setZumbido(true);
                contacModel.set(i, c);
                break;
            }
        }
        jContactos.repaint();
    }
    private void filtrarContactos() {
        String filtro = jtBuscadorContactos.getText().toLowerCase().trim();
        contacModel.clear();
        if (filtro.isEmpty()) {
            for (Contact c : todosLosContactos) {
                contacModel.addElement(c);
            }
        } else {
            for (Contact c : todosLosContactos) {
                if (c.getName() != null && c.getName().toLowerCase().contains(filtro)) {
                    contacModel.addElement(c);
                }
            }
        }
        jContactos.repaint();
    }
    public void actualizarValores(String idUsuarioActual) {
        this.idUsuarioActual = idUsuarioActual;
    }

    public void mostrarMensajeSistema(String texto) {
        jPanelChat.add(styles.crearPanelMensajeSistema(texto));
        jPanelChat.revalidate();
        jPanelChat.repaint();
    }
    private JComponent crearFotoPerfilyo() {
        return styles.crearFotoPerfilYo(Mediador.NOMBRE);
    }
    private JComponent crearFotoPerfil() {
        return styles.crearFotoPerfil(lblContactoSeleccionado.getText());
    }
    private JPanel crearFilaMensaje(String texto, boolean esMio, String fechaHora, boolean leido, String idMensaje) {
        JPanel fila = new JPanel() {
            @Override
            public Dimension getMaximumSize() {
                return new Dimension(Integer.MAX_VALUE, getPreferredSize().height);
            }
        };
        fila.setLayout(new BoxLayout(fila, BoxLayout.X_AXIS));
        fila.setOpaque(false);
        fila.setBorder(BorderFactory.createEmptyBorder(4, 12, 4, 12));
        fila.setMaximumSize(new Dimension(Integer.MAX_VALUE, fila.getPreferredSize().height));

        String soloHora = formatearSoloHora(fechaHora);
        JPanel bubble = styles.crearBurbuja(texto, esMio, soloHora, leido, idMensaje);

        // ── Popup de acciones sobre la burbuja ──
        JPopupMenu popupMensaje = new JPopupMenu();
        styles.stylePopupMenu(popupMensaje);
        if (esMio && !texto.equals("Eliminaste este mensaje")) {
            JMenuItem itemEliminar = styles.createMenuItem("Eliminar mensaje");
            itemEliminar.addActionListener(e -> {
                boolean eliminar = showEliminarMensajePopup();
                if (eliminar) {
                    // Buscar el JLabel dentro de la burbuja para actualizar el texto
                    actualizarTextoBurbuja(bubble, "<html><body style='max-width:230px; color:#6b7280; font-style:italic;'>Eliminaste este mensaje</body></html>");
                    this.chatsController.eliminarMensajeBD(idMensaje);
                    EliminarMensaje eliminarMensaje = new EliminarMensaje(idMensaje);
                    Mediador.getInstance().sendMessage(idUsuarioActual, eliminarMensaje);
                }
            });
            popupMensaje.add(itemEliminar);
        }
        if (!texto.equals("Eliminaste este mensaje") && !texto.equals("Se elimino este mensaje")) {
            JMenuItem itemFijar = styles.createMenuItem("Fijar mensaje");
            itemFijar.addActionListener(e -> {
                fijarMensajeUI(idMensaje, texto);
                FijarMensaje fijarMsg = new FijarMensaje(idMensaje);
                Mediador.getInstance().sendMessage(idUsuarioActual, fijarMsg);
            });
            popupMensaje.add(itemFijar);
        }
        bubble.addMouseListener(new MouseAdapter() {
            private void mostrarPopup(MouseEvent e) {
                if (SwingUtilities.isRightMouseButton(e)) popupMensaje.show(bubble, e.getX(), e.getY());
            }
            @Override public void mousePressed(MouseEvent e) { mostrarPopup(e); }
            @Override public void mouseReleased(MouseEvent e) { mostrarPopup(e); }
        });

        bubble.setAlignmentY(Component.BOTTOM_ALIGNMENT);
        JComponent foto = esMio ? crearFotoPerfilyo() : crearFotoPerfil();
        foto.setAlignmentY(Component.BOTTOM_ALIGNMENT);
        if (esMio) {
            fila.add(Box.createHorizontalGlue());
            fila.add(bubble);
            fila.add(Box.createHorizontalStrut(6));
            fila.add(foto);
        } else {
            fila.add(foto);
            fila.add(Box.createHorizontalStrut(6));
            fila.add(bubble);
            fila.add(Box.createHorizontalGlue());
        }
        return fila;
    }
    private void actualizarTextoBurbuja(JPanel bubble, String nuevoHtml) {
        for (Component c : bubble.getComponents()) {
            if (c instanceof JPanel contenido) {
                for (Component inner : contenido.getComponents()) {
                    if (inner instanceof JLabel lbl) {
                        lbl.setText(nuevoHtml);
                        bubble.revalidate();
                        bubble.repaint();
                        return;
                    }
                    if (inner instanceof JPanel subPanel) {
                        for (Component sub : subPanel.getComponents()) {
                            if (sub instanceof JLabel lbl2) {
                                lbl2.setText(nuevoHtml);
                                bubble.revalidate();
                                bubble.repaint();
                                return;
                            }
                        }
                    }
                }
            }
        }
    }
    private String formatearSoloHora(String fechaHora) {
        try {
            java.time.LocalDateTime dateTime =
                    java.time.LocalDateTime.parse(fechaHora, java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
            return dateTime.format(java.time.format.DateTimeFormatter.ofPattern("HH:mm"));
        } catch (Exception e) {
            return fechaHora;
        }
    }
    public void agregarMensajeUI(String texto, boolean esMio, String fechaHora, boolean leido, String idMensaje) {
        JPanel mensaje = crearFilaMensaje(texto, esMio, fechaHora, leido, idMensaje);
        jPanelChat.add(mensaje);
        jPanelChat.revalidate();
        jPanelChat.repaint();
        SwingUtilities.invokeLater(() -> {
            JScrollBar vertical = jScrollPaneChat.getVerticalScrollBar();
            vertical.setValue(vertical.getMaximum());
        });
    }
    private void limpiarChat() {
        jPanelChat.removeAll();
        jPanelChat.revalidate();
        jPanelChat.repaint();
        mensajeFijadoId = null;
        mensajeFijadoTexto = null;
        if (panelMensajeFijado != null) panelMensajeFijado.setVisible(false);
    }

    public void agregarMensajeUnicoUI(boolean esMio, String fechaHora, boolean leido, String idMensaje) {
        JPanel fila = crearFilaMensajeUnico(esMio, fechaHora, leido, idMensaje);
        jPanelChat.add(fila);
        jPanelChat.revalidate();
        jPanelChat.repaint();
        SwingUtilities.invokeLater(() -> {
            JScrollBar vertical = jScrollPaneChat.getVerticalScrollBar();
            vertical.setValue(vertical.getMaximum());
        });
    }
    private JPanel crearFilaMensajeUnico(boolean esMio, String fechaHora, boolean leido, String idMensaje) {
        JPanel fila = new JPanel() {
            @Override
            public Dimension getMaximumSize() {
                return new Dimension(Integer.MAX_VALUE, getPreferredSize().height);
            }
        };
        fila.setLayout(new BoxLayout(fila, BoxLayout.X_AXIS));
        fila.setOpaque(false);
        fila.setBorder(BorderFactory.createEmptyBorder(4, 12, 4, 12));

        String soloHora = formatearSoloHora(fechaHora);
        boolean yaLeido = Mediador.getInstance().mensajeLeido(idMensaje);
        JPanel bubble = styles.crearBurbujaUnica(esMio, soloHora, leido, idMensaje, yaLeido);
        bubble.setAlignmentY(Component.BOTTOM_ALIGNMENT);
        JComponent foto = esMio ? crearFotoPerfilyo() : crearFotoPerfil();
        foto.setAlignmentY(Component.BOTTOM_ALIGNMENT);
        if (esMio) {
            fila.add(Box.createHorizontalGlue());
            fila.add(bubble);
            fila.add(Box.createHorizontalStrut(6));
            fila.add(foto);
        } else {
            fila.add(foto);
            fila.add(Box.createHorizontalStrut(6));
            fila.add(bubble);
            fila.add(Box.createHorizontalGlue());
        }
        return fila;
    }
    public void agregarMensajeUnicoUIBoton(String mensaje, boolean esMio, String fechaHora, boolean leido, String idMensaje) {
        JPanel fila = crearFilaMensajeUnicoBoton(mensaje, esMio, fechaHora, leido, idMensaje);
        jPanelChat.add(fila);
        jPanelChat.revalidate();
        jPanelChat.repaint();
        SwingUtilities.invokeLater(() -> {
            JScrollBar vertical = jScrollPaneChat.getVerticalScrollBar();
            vertical.setValue(vertical.getMaximum());
        });
    }

    private JPanel crearFilaMensajeUnicoBoton(String mensaje, boolean esMio, String fechaHora, boolean leido, String idMensaje) {
        JPanel fila = new JPanel() {
            @Override
            public Dimension getMaximumSize() {
                return new Dimension(Integer.MAX_VALUE, getPreferredSize().height);
            }
        };
        fila.setLayout(new BoxLayout(fila, BoxLayout.X_AXIS));
        fila.setOpaque(false);
        fila.setBorder(BorderFactory.createEmptyBorder(4, 12, 4, 12));

        String soloHora = formatearSoloHora(fechaHora);
        boolean yaLeido = Mediador.getInstance().mensajeLeido(idMensaje);
        JButton btn = styles.crearBotonMensajeUnico(soloHora, esMio, leido, idMensaje, yaLeido);

        if (!yaLeido) {
            btn.addActionListener(e -> {
                showMensajeUnicoPopup(mensaje);
                ConfirmarRecibido confirmarRecibido = new ConfirmarRecibido(idMensaje);
                Mediador.getInstance().sendMessage(idUsuarioActual, confirmarRecibido);
                Mediador.getInstance().actualizarLeidoBd(confirmarRecibido.getIdMensaje());
                btn.setEnabled(false);
                btn.setToolTipText("El mensaje ya fue leído");
                btn.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                // Actualizar labels dentro del botón
                actualizarLabelsBotonUnico(btn);
                btn.revalidate();
                btn.repaint();
            });
        }

        JPanel contenedor = new JPanel(new FlowLayout(esMio ? FlowLayout.RIGHT : FlowLayout.LEFT, 0, 0));
        contenedor.setOpaque(false);
        contenedor.add(btn);
        contenedor.setAlignmentY(Component.BOTTOM_ALIGNMENT);

        JComponent foto = esMio ? crearFotoPerfilyo() : crearFotoPerfil();
        foto.setAlignmentY(Component.BOTTOM_ALIGNMENT);
        if (esMio) {
            fila.add(Box.createHorizontalGlue());
            fila.add(contenedor);
            fila.add(Box.createHorizontalStrut(6));
            fila.add(foto);
        } else {
            fila.add(foto);
            fila.add(Box.createHorizontalStrut(6));
            fila.add(contenedor);
            fila.add(Box.createHorizontalGlue());
        }
        return fila;
    }
    private void actualizarLabelsBotonUnico(JButton btn) {
        for (Component c : btn.getComponents()) {
            if (c instanceof JPanel panel) {
                for (Component inner : panel.getComponents()) {
                    if (inner instanceof JPanel subPanel) {
                        for (Component sub : subPanel.getComponents()) {
                            if (sub instanceof JLabel lbl) {
                                if (lbl.getText() != null && lbl.getText().contains("Mensaje")) {
                                    lbl.setText("<html><body style='color:#6b7280; font-family:Tahoma; font-style:italic;'>Mensaje visto</body></html>");
                                }
                                if (lbl.getText() != null && lbl.getText().contains("⏱")) {
                                    lbl.setForeground(new Color(107, 114, 128));
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    public void fijarMensajeUI(String idMensaje, String texto) {
        Mediador.getInstance().desfijarMensajes();
        mensajeFijadoId = idMensaje;
        mensajeFijadoTexto = texto;
        String textoCortado = texto.length() > 95 ? texto.substring(0, 90) + "…" : texto;
        lblMensajeFijado.setText(textoCortado);
        panelMensajeFijado.setVisible(true);
        panelMensajeFijado.revalidate();
        panelMensajeFijado.repaint();
        panelMensajeFijado.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Mediador.getInstance().actualizarFijado(idMensaje, true);
        for (MouseListener ml : panelMensajeFijado.getMouseListeners()) {
            panelMensajeFijado.removeMouseListener(ml);
        }
        panelMensajeFijado.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                scrollAlMensajeFijado(idMensaje);
            }
        });
    }
    private void scrollAlMensajeFijado(String idMensaje) {
        for (Component filaComp : jPanelChat.getComponents()) {
            if (!(filaComp instanceof JPanel fila)) continue;
            for (Component contenedorComp : fila.getComponents()) {
                if (!(contenedorComp instanceof JPanel contenedor)) continue;
                for (Component bubbleComp : contenedor.getComponents()) {
                    if (!(bubbleComp instanceof JPanel bubble)) continue;
                    for (Component inner : bubble.getComponents()) {
                        if (inner instanceof JLabel lbl && idMensaje.equals(lbl.getName())) {
                            Rectangle bounds = fila.getBounds();
                            SwingUtilities.invokeLater(() ->
                                    jScrollPaneChat.getVerticalScrollBar().setValue(bounds.y)
                            );
                            return;
                        }
                    }
                }
            }
        }
    }
    private void desfijarMensaje() {
        Mediador.getInstance().actualizarFijado(mensajeFijadoId, false);
        mensajeFijadoId = null;
        mensajeFijadoTexto = null;
        panelMensajeFijado.setVisible(false);
    }

    public void actualizarChecksAzules(String idMensaje) {
        for (Component filaComp : jPanelChat.getComponents()) {
            if (!(filaComp instanceof JPanel fila)) continue;
            for (Component comp : fila.getComponents()) {
                if (!(comp instanceof JPanel bubble)) continue;
                for (Component bubbleChild : bubble.getComponents()) {
                    if (!(bubbleChild instanceof JPanel contenidoInterno)) continue;
                    for (Component innerComp : contenidoInterno.getComponents()) {
                        if (!(innerComp instanceof JPanel panelInf)) continue;
                        for (Component checkComp : panelInf.getComponents()) {
                            if (checkComp instanceof JLabel lbl && idMensaje.equals(lbl.getName())) {
                                lbl.setText("✔✔");
                                lbl.setForeground(new Color(167, 243, 208));
                                panelInf.revalidate();
                                panelInf.repaint();
                                return;
                            }
                        }
                    }
                }
            }
        }
    }
    public void actualizarMensajeEliminado(String idMensaje) {
        for (Component filaComp : jPanelChat.getComponents()) {
            if (!(filaComp instanceof JPanel fila)) continue;
            for (Component comp : fila.getComponents()) {
                if (!(comp instanceof JPanel bubble)) continue;
                for (Component bubbleChild : bubble.getComponents()) {
                    if (!(bubbleChild instanceof JPanel contenidoInterno)) continue;
                    Component[] innerComps = contenidoInterno.getComponents();
                    if (innerComps.length == 0) continue;
                    if (!(innerComps[0] instanceof JLabel lblTexto)) continue;
                    if (idMensaje.equals(lblTexto.getName())) {
                        SwingUtilities.invokeLater(() -> {
                            lblTexto.setText("<html><body style='max-width:220px; color:#6b7280; font-style:italic; font-family:Tahoma;'>Se eliminó este mensaje</body></html>");
                            bubble.revalidate();
                            bubble.repaint();
                        });
                        return;
                    }
                }
            }
        }
    }
    public void actualizarBurbujaUnicaLeida(String idMensaje) {
        for (Component filaComp : jPanelChat.getComponents()) {
            if (!(filaComp instanceof JPanel fila)) continue;
            for (Component comp : fila.getComponents()) {
                if (!(comp instanceof JPanel bubble)) continue;
                for (Component bubbleChild : bubble.getComponents()) {
                    if (!(bubbleChild instanceof JPanel contenidoInterno)) continue;
                    for (Component innerComp : contenidoInterno.getComponents()) {
                        if (!(innerComp instanceof JPanel panelTexto)) continue;
                        boolean encontrado = false;
                        for (Component labelComp : panelTexto.getComponents()) {
                            if (labelComp instanceof JLabel lbl) {
                                String name = lbl.getName();
                                if (name != null) {
                                    if (name.equals(idMensaje + "texto")) {
                                        lbl.setText("<html><body style='color:#6b7280; font-family:Tahoma; font-style:italic;'>Mensaje visto</body></html>");
                                        encontrado = true;
                                    }
                                    if (name.equals(idMensaje + "icono")) {
                                        lbl.setForeground(new Color(107, 114, 128));
                                        encontrado = true;
                                    }
                                }
                            }
                        }
                        if (encontrado) {
                            panelTexto.revalidate();
                            panelTexto.repaint();
                            return;
                        }
                    }
                }
            }
        }
    }

    public void ejecutarEfectoZumbido() {
        final Point posicionOriginal = getLocation();
        new Thread(() -> reproducirSonidoZumbido()).start();
        Timer timerVibracion = new Timer(20, null);
        final long tiempoInicio = System.currentTimeMillis();
        final int duracion = 1000;
        final int intensidad = 5;
        timerVibracion.addActionListener(e -> {
            long tiempoTranscurrido = System.currentTimeMillis() - tiempoInicio;
            if (tiempoTranscurrido >= duracion) {
                ((Timer) e.getSource()).stop();
                setLocation(posicionOriginal);
            } else {
                int dx = (int) (Math.random() * intensidad * 2) - intensidad;
                int dy = (int) (Math.random() * intensidad * 2) - intensidad;
                setLocation(posicionOriginal.x + dx, posicionOriginal.y + dy);
            }
        });
        timerVibracion.start();
    }
    private void reproducirSonidoZumbido() {
        try {
            float sampleRate = 8000f;
            int duracionMs = 1000;
            byte[] buf = new byte[(int) (sampleRate * duracionMs / 1000)];
            for (int i = 0; i < buf.length; i++) {
                double angle = i / (sampleRate / 262) * 2.0 * Math.PI;
                double modulacion = Math.sin(i / (sampleRate / 15) * 2.0 * Math.PI);
                buf[i] = (byte) (Math.sin(angle) * 80 * (0.5 + 0.5 * modulacion));
            }
            javax.sound.sampled.AudioFormat af = new javax.sound.sampled.AudioFormat(
                    sampleRate, 8, 1, true, false
            );
            javax.sound.sampled.DataLine.Info info = new javax.sound.sampled.DataLine.Info(
                    javax.sound.sampled.SourceDataLine.class, af
            );
            javax.sound.sampled.SourceDataLine sdl = (javax.sound.sampled.SourceDataLine)
                    javax.sound.sampled.AudioSystem.getLine(info);
            sdl.open(af);
            sdl.start();
            sdl.write(buf, 0, buf.length);
            sdl.drain();
            sdl.close();
        } catch (Exception e) {
            java.awt.Toolkit.getDefaultToolkit().beep();
        }
    }

//     Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jBtnEnviar;
    private JTextField jtMensaje;
    private JPanel jPanelChat;
    private JScrollPane jScrollPaneChat;
    private JButton jBtnNuevaConexion;
    private JButton jBtnOff;
    public JList<Contact> jContactos;
    private JPopupMenu jPopupMenu;
    private JMenuItem itemZumbido;
    private JMenuItem itemHello;
    private JMenuItem itemInvitacion;
    private JMenuItem itemEnviarContacto;
    private JMenuItem itemActualizarIp;
    private JButton jBtnConectar;
    private JButton jBtnAceptar;
    private JTextField jtIp;
    private JTextField jtName;
    private JTextField jtNameEnviarContacto;
    private JButton jBtnEnviarContacto;
    private JLabel lblContactoSeleccionado;
    private String mensajeFijadoId = null;
    private String mensajeFijadoTexto = null;
    private JPanel panelMensajeFijado;
    private JLabel lblMensajeFijado;
    private JButton jBtnMensajeUnico;
    public boolean modoMensajeUnico = false;
    private JTextField jtBuscadorContactos;
    private List<Contact> todosLosContactos = new java.util.ArrayList<>();
    private JButton jBtnTheme;
    private JPanel panelContactos;
    private JPanel panelChat;
    private JPanel panelSuperior;
    private JPanel panelInferior;
    private JPanel sidebarHeader;
    private JScrollPane scrollContactos;

    public void onMessage(Message message) {
        if (message instanceof Aceptar)
            showAcceptPopup();
        if (message instanceof Rechazar)
            showDeclinePopup();
        if (message instanceof RechazarHello)
            showHelloRechazadoPopup();
        if (message instanceof Mensaje) {
            Mensaje mensaje = (Mensaje) message;
            if (!mensaje.getIdUsuario().equals(idUsuarioActual) || jContactos.getSelectedValue() == null) {
                marcarContactoConMensajeNuevo(mensaje.getIdUsuario());
            }
            if (mensaje.getIdUsuario().equals(idUsuarioActual) && !idUsuarioActual.equals(Mediador.ID_MIO) && jContactos.getSelectedValue() != null) {
                agregarMensajeUI(mensaje.getMensaje(), false, Mediador.getInstance().obtenerHoraActual(), false, mensaje.getIdMensaje());
            }
            if (!idUsuarioActual.equals(Mediador.ID_MIO)) {
                chatsController.guardarEnBd(mensaje.getIdMensaje(), mensaje.getMensaje(), mensaje.getIdUsuario(), Mediador.ID_MIO, Mediador.getInstance().obtenerHoraActual(), false);
            }
            if (mensaje.getIdUsuario().equals(idUsuarioActual) && jContactos.getSelectedValue() != null) {
                ConfirmarRecibido confirmarRecibido = new ConfirmarRecibido(mensaje.getIdMensaje());
                System.out.println("Enviando 008...");
                Mediador.getInstance().sendMessage(idUsuarioActual, confirmarRecibido);
                Mediador.getInstance().actualizarLeidoBd(mensaje.getIdMensaje());
            }
        }
        if (message instanceof ConfirmarRecibido) {
            ConfirmarRecibido confirmarRecibido = (ConfirmarRecibido) message;
            SwingUtilities.invokeLater(() -> {
                actualizarChecksAzules(((ConfirmarRecibido) message).getIdMensaje());
                actualizarBurbujaUnicaLeida(confirmarRecibido.getIdMensaje());
            });
        }
        if (message instanceof FueraLinea) {
            System.out.println("Conexión terminada por cliente");
            showOffPopup();
            mostrarMensajeSistema("CONEXION TERMINADA");
            actualizarEstadoContacto(idUsuarioActual, false);
        }
        if (message instanceof EnviarContacto) {
            System.out.println("contacto agregado");
            EnviarContacto enviarContacto = (EnviarContacto) message;
            Contact nuevo = new Contact(
                    enviarContacto.getIdUsuario(),
                    enviarContacto.getNombreCliente(),
                    enviarContacto.getIp(),
                    false,
                    false,
                    false
            );
            SwingUtilities.invokeLater(() -> {
                agregarContacto(nuevo);
                jContactos.revalidate();
                jContactos.repaint();
            });
            showAgregarContactoPopup();
        }
        if (message instanceof EliminarMensaje) {
            EliminarMensaje eliminarMensaje = (EliminarMensaje) message;
            this.chatsController.mensajeeliminadoPorCLiente(eliminarMensaje.getIdMensaje());
            actualizarMensajeEliminado(eliminarMensaje.getIdMensaje());
        }
        if (message instanceof MensajeUnico) {
            MensajeUnico mensajeUnico = (MensajeUnico) message;
            if (!mensajeUnico.getIdUsuario().equals(idUsuarioActual) || jContactos.getSelectedValue() == null) {
                marcarContactoConMensajeNuevo(mensajeUnico.getIdUsuario());
            }
            Mediador.getInstance().updateUnico(mensajeUnico.getIdMensaje());
            if (mensajeUnico.getIdUsuario().equals(idUsuarioActual) && !idUsuarioActual.equals(Mediador.ID_MIO) && jContactos.getSelectedValue() != null) {
                agregarMensajeUnicoUIBoton(mensajeUnico.getMensaje(), false, Mediador.getInstance().obtenerHoraActual(), false, mensajeUnico.getIdMensaje());
            }
            if (!idUsuarioActual.equals(Mediador.ID_MIO)) {
                chatsController.guardarEnBd(mensajeUnico.getIdMensaje(), mensajeUnico.getMensaje(), mensajeUnico.getIdUsuario(), Mediador.ID_MIO, Mediador.getInstance().obtenerHoraActual(), true);
            }
        }
        if (message instanceof CambiarTema) {
            CambiarTema cambiarTema = (CambiarTema) message;
            String tema = cambiarTema.getIdTema();
            switch (tema) {
                case "1": ThemeManager.setTheme(ThemeManager.Theme.UNO); aplicarTema(); break;
                case "2": ThemeManager.setTheme(ThemeManager.Theme.DOS); aplicarTema(); break;
                case "3": ThemeManager.setTheme(ThemeManager.Theme.CUATRO); aplicarTema(); break;
                case "4": ThemeManager.setTheme(ThemeManager.Theme.TRES); aplicarTema(); break;
                case "5": ThemeManager.setTheme(ThemeManager.Theme.CINCO); aplicarTema(); break;
            }
        }
    }
    @Override
    public void onloadContacts(List<Contact> contacts) {
        try {
            if (contacts.isEmpty())
                System.out.println("BD vacia");
            todosLosContactos.clear();
            todosLosContactos.addAll(contacts);
            contacModel.clear();
            contacModel.addAll(contacts);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    @Override
    public void onloadMessages(List<Chats> chats) {
        limpiarChat();
        String ultimaFecha = "";
        if (jContactos.getSelectedValue() == null)
            return;
        for (Chats c : chats) {
            boolean esMio = c.getIdEmisor().equals(Mediador.ID_MIO);
            boolean leido = c.getLeido().equals("1");
            boolean fijado = c.getFijado().equals("1");
            boolean unico = c.getUnico().equals("1");
            if (unico) {
                if (esMio) {
                    agregarMensajeUnicoUI(esMio, c.getHora(), leido, c.getIdMensaje());
                } else {
                    agregarMensajeUnicoUIBoton(c.getMensajeTxt(), esMio, c.getHora(), leido, c.getIdMensaje());
                }
            } else {
                agregarMensajeUI(c.getMensajeTxt(), esMio, c.getHora(), leido, c.getIdMensaje());
            }
            if (!esMio && !leido && !unico && jContactos.getSelectedValue() != null) {
                System.out.println(jContactos.getSelectedValue() + "lalal");
                System.out.println("Enviando 008...");
                ConfirmarRecibido confirmarRecibido = new ConfirmarRecibido(c.getIdMensaje());
                Mediador.getInstance().sendMessage(c.getIdEmisor(), confirmarRecibido);
                Mediador.getInstance().actualizarLeidoBd(c.getIdMensaje());
            }
            if (fijado)
                fijarMensajeUI(c.getIdMensaje(), c.getMensajeTxt());
        }
    }
    // End of variables declaration//GEN-END:variables
}
