/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upb.chatupb_v2.view;

import edu.upb.chatupb_v2.model.entities.message.Aceptar;
import edu.upb.chatupb_v2.model.entities.message.Invitacion;
import edu.upb.chatupb_v2.model.entities.message.Message;
import edu.upb.chatupb_v2.model.entities.message.Rechazar;
import edu.upb.chatupb_v2.controller.Mediador;
import edu.upb.chatupb_v2.model.network.SocketClient;
//import edu.upb.chatupb_v2.bl.server.SocketListener;

import javax.swing.*;
import java.awt.*;

public class ChatUI extends javax.swing.JFrame {
//    ChatServer chatServer;
//    ListaNegraDao listaNegraDao = new ListaNegraDao(ConnectionDB.getInstance().getConection());;

    /**
     * Creates new form ChatUI
     */
    public ChatUI() {
        initComponents();
//        try{
//            chatServer = new ChatServer();
//            chatServer.addListener(this);
//            chatServer.start();
//        }catch(Exception e){
//            e.printStackTrace();
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

            setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        setSize(420, 450);
        setLocationRelativeTo(null);
        setLayout(null);
        getContentPane().setBackground(new java.awt.Color(240,240,240));

        // ===== CARD PANEL =====
        JPanel card = new JPanel();
        card.setLayout(null);
        card.setBackground(Color.WHITE);
        card.setBounds(35, 80, 350, 300);
        card.setBorder(BorderFactory.createLineBorder(new Color(220,220,220), 1, true));

        // ===== IMAGEN =====
        JLabel imageLabel = new JLabel();
        imageLabel.setHorizontalAlignment(SwingConstants.CENTER);
        imageLabel.setBounds(155, 20, 110, 110);

        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/robotAdd.png"));
            Image img = icon.getImage().getScaledInstance(110, -1, Image.SCALE_SMOOTH);
            imageLabel.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            imageLabel.setText("Imagen no encontrada");
        }

        // ===== TITULO =====
        JLabel title = new JLabel("Add Contact");
        title.setFont(new Font("Arial", Font.BOLD, 18));
        title.setBounds(110, 70, 200, 30);


        // ===== IP =====
        JLabel ipLabel = new JLabel("Contact IP:");
        ipLabel.setFont(new Font("Arial", Font.PLAIN, 13));
        ipLabel.setBounds(30, 170, 200, 20);

        jtIp = new JTextField();
        jtIp.setBounds(30, 190, 290, 30);

        // ===== BOTON =====
        jBtnConectar = new JButton("CONECTAR");
        jBtnConectar.setBounds(75, 235, 200, 35);
        jBtnConectar.setBackground(Color.GRAY);
        jBtnConectar.setForeground(Color.BLACK);
        jBtnConectar.setFocusPainted(false);

        jBtnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConectarActionPerformed(evt);
            }
        });

        // ===== AGREGAMOS AL CARD =====
        card.add(title);
        card.add(ipLabel);
        card.add(jtIp);
        card.add(jBtnConectar);

        // ===== AGREGAMOS AL FRAME =====
        add(imageLabel);
        add(card);
    }// </editor-fold>//GEN-END:initComponents
    private void showAcceptPopup() {

        JDialog dialog = new JDialog(this, true);
        dialog.setSize(320, 300);
        dialog.setLocationRelativeTo(this);
        dialog.setUndecorated(true);
        dialog.setBackground(new Color(0,0,0,0));

        JPanel root = new JPanel(null);
        root.setOpaque(false);

        // ===== CARD =====
        JPanel card = new JPanel();
        card.setLayout(null);
        card.setBackground(Color.WHITE);
        card.setBounds(40, 90, 220, 110);
        card.setBorder(BorderFactory.createLineBorder(new Color(220,220,220), 1, true));

        // ===== TITULO =====
        JLabel title = new JLabel("Conexion aceptada");
        title.setFont(new Font("Arial", Font.BOLD, 16));
        title.setForeground(new Color(37,29,75));
        title.setHorizontalAlignment(SwingConstants.CENTER);
        title.setBounds(20, 20, 180, 30);

        // ===== BOTON OK =====
        JButton okButton = new JButton("Ok");
        okButton.setBounds(85, 60, 50, 30);
        okButton.setBackground(new Color(202,203,233));
        okButton.setFocusPainted(false);

        okButton.addActionListener(e -> dialog.dispose());

        card.add(title);
        card.add(okButton);

        // ===== IMAGEN =====
        JLabel imageLabel = new JLabel();
        imageLabel.setBounds(85, 0, 110, 110);

        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/robotAccept.png"));
            Image img = icon.getImage().getScaledInstance(110, -1, Image.SCALE_SMOOTH);
            imageLabel.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            imageLabel.setText("Img");
        }

        root.add(card);
        root.add(imageLabel);

        dialog.add(root);
        dialog.setVisible(true);
    }
    private void showDeclinePopup() {

        JDialog dialog = new JDialog(this, true);
        dialog.setSize(320, 300);
        dialog.setLocationRelativeTo(this);
        dialog.setUndecorated(true);
        dialog.setBackground(new Color(0,0,0,0));

        JPanel root = new JPanel(null);
        root.setOpaque(false);

        // ===== CARD =====
        JPanel card = new JPanel();
        card.setLayout(null);
        card.setBackground(Color.WHITE);
        card.setBounds(40, 90, 220, 110);
        card.setBorder(BorderFactory.createLineBorder(new Color(220,220,220), 1, true));

        // ===== TITULO =====
        JLabel title = new JLabel("Conexion rechazada");
        title.setFont(new Font("Arial", Font.BOLD, 16));
        title.setForeground(new Color(37,29,75));
        title.setHorizontalAlignment(SwingConstants.CENTER);
        title.setBounds(20, 20, 180, 30);

        // ===== BOTON OK =====
        JButton okButton = new JButton("Ok");
        okButton.setBounds(85, 60, 50, 30);
        okButton.setBackground(new Color(202,203,233));
        okButton.setFocusPainted(false);

        okButton.addActionListener(e -> dialog.dispose());

        card.add(title);
        card.add(okButton);

        // ===== IMAGEN =====
        JLabel imageLabel = new JLabel();
        imageLabel.setBounds(85, 0, 110, 110);

        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/robotDecline.png"));
            Image img = icon.getImage().getScaledInstance(110, -1, Image.SCALE_SMOOTH);
            imageLabel.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            imageLabel.setText("Img");
        }

        root.add(card);
        root.add(imageLabel);

        dialog.add(root);
        dialog.setVisible(true);
    }
    private boolean showInvitationPopup(String nombreInvitador) {

        final boolean[] accepted = {false};

        JDialog dialog = new JDialog(this, true);
        dialog.setSize(350, 320);
        dialog.setLocationRelativeTo(this);
        dialog.setUndecorated(true);
        dialog.setBackground(new Color(0,0,0,0));

        JPanel root = new JPanel(null);
        root.setOpaque(false);

        // ===== CARD =====
        JPanel card = new JPanel();
        card.setLayout(null);
        card.setBackground(Color.WHITE);
        card.setBounds(40, 100, 270, 150);
        card.setBorder(BorderFactory.createLineBorder(new Color(220,220,220), 1, true));

        // ===== TITULO =====
        JLabel title = new JLabel("Llegó la invitación: " + nombreInvitador);
        title.setFont(new Font("Arial", Font.BOLD, 14));
        title.setForeground(new Color(37,29,75));
        title.setHorizontalAlignment(SwingConstants.CENTER);
        title.setBounds(20, 20, 230, 40);

        // ===== BOTON ACCEPT =====
        JButton acceptButton = new JButton("Aceptar");
        acceptButton.setBounds(30, 80, 90, 35);
        acceptButton.setBackground(Color.lightGray);
        acceptButton.setForeground(Color.BLACK);
        acceptButton.setFocusPainted(false);

        acceptButton.addActionListener(e -> {
            accepted[0] = true;
            dialog.dispose();
        });

        // ===== BOTON DECLINE =====
        JButton declineButton = new JButton("Rechazar");
        declineButton.setBounds(150, 80, 90, 35);
        declineButton.setBackground(Color.GRAY);
        declineButton.setForeground(Color.BLACK);
        declineButton.setFocusPainted(false);

        declineButton.addActionListener(e -> {
            accepted[0] = false;
            dialog.dispose();
        });

        card.add(title);
        card.add(acceptButton);
        card.add(declineButton);

        // ===== IMAGEN =====
        JLabel imageLabel = new JLabel();
        imageLabel.setBounds(120, 0, 110, 110);

        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/robotRequest.png"));
            Image img = icon.getImage().getScaledInstance(110, -1, Image.SCALE_SMOOTH);
            imageLabel.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            imageLabel.setText("Img");
        }

        root.add(card);
        root.add(imageLabel);

        dialog.add(root);
        dialog.setVisible(true);

        return accepted[0];
    }

//    // @SuppressWarnings("unchecked")

    private void jBtnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConectarActionPerformed
        System.out.println("Enviando 001...");
        Mediador.getInstance().establecerConexion(jtIp.getText().toString(), Mediador.getInstance().getIdMio(), Mediador.getInstance().getNombre());
//        try {
//            iniciarCliente();
//            client = new SocketClient(jtIp.getText().toString());
//            client.addListener(this); // le estoy pasando una instancia de si mismo. se subscribe al socketclient ue se acaba de crear
//            client.start();
//            System.out.println("Enviando 001...");
//            Message message = new Invitacion(idMio, nombre);
//            client.send(message);
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_jBtnConectarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChatUI().setVisible(true);
//            }
//        });
//    }

//     Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConectar;
    private javax.swing.JTextField jtIp;

    public void onMessage(SocketClient socketClient, Message message) {
        if (message instanceof Invitacion) {
            System.out.println("Paso 1: Llego la invitacion");

            Invitacion invitacion = (Invitacion) message;
//            int respuesta = JOptionPane.showConfirmDialog(
//                    this,
//                    "LLego la invitacion: " + invitacion
//                    , "Invitacion",
//                    JOptionPane.YES_NO_OPTION); // esto le llega al CLiente

//            try {
//                if (listaNegraDao.estaBloqueado(idMio, invitacion.getIdUsuario())) {
//                    System.out.println("Usuario bloqueado automáticamente.");
//                    Message rechazar = new Rechazar();
//                    socketClient.send(rechazar);
//                    return;
//                }
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
            boolean accepted = showInvitationPopup(invitacion.getNombre());
            if (accepted) {
                System.out.println("Paso 2: Aceptar Invitacion");
                System.out.println("id invitacion: " + invitacion.getIdUsuario());
                Mediador.getInstance().addClient(invitacion.getIdUsuario(), invitacion.getNombre(), socketClient);
                Message aceptar = new Aceptar(Mediador.getInstance().getIdMio(), Mediador.getInstance().getNombre());
                Mediador.getInstance().sendMessage(invitacion.getIdUsuario(), aceptar);
                System.out.println("Enviando 002...");
                Mediador.getInstance().getChatView().actualizarValores(invitacion.getIdUsuario());
                Mediador.getInstance().getChatView().setVisible(true);
                this.setVisible(false);
//                client.removeListener(this);
            } else  {
                System.out.println("Paso 2: Rechazar Invitacion");
//                Mediador.getInstance().listaNegra.add(socketClient);
                System.out.println("Enviando 003...");
                try {
                    //PREGUNTAR PROFE
                    Message rechazar = new Rechazar();
                    socketClient.send(rechazar);
                } catch (Exception e) {
                    e.printStackTrace();
                }

//                try {
//                    listaNegraDao.agregarBloqueado(idMio, idUsuarioActivo);
//                    Message rechazar = new Rechazar();
//                    socketClient.send(rechazar);
//                } catch (Exception e) {
//                    e.printStackTrace();
//                }
//                System.out.println("Lista negra: " + Mediador.getInstance().listaNegra);
            }
        }
        if (message instanceof Aceptar) {
//            JOptionPane.showMessageDialog(null, "Su invitacion fue aceptada", "Aceptada", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Entra en 002 Aceptar");
            showAcceptPopup();
            Aceptar aceptar = (Aceptar) message;
            Mediador.getInstance().getChatView().actualizarValores(aceptar.getIdUsuario());
            Mediador.getInstance().addClient(aceptar.getIdUsuario(), aceptar.getNombre(), socketClient);
            Mediador.getInstance().getChatView().setVisible(true);
            this.setVisible(false);
        }
        if  (message instanceof Rechazar) {
            System.out.println("Entra en 003 Solicitud Rechazada");
            showDeclinePopup();
        }
    }
    // End of variables declaration//GEN-END:variables
}

