/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upb.chatupb_v2.view;

import edu.upb.chatupb_v2.controller.ChatsController;
import edu.upb.chatupb_v2.controller.ContactController;
import edu.upb.chatupb_v2.model.entities.message.FueraLinea;
import edu.upb.chatupb_v2.model.entities.message.Hello;
import edu.upb.chatupb_v2.model.entities.message.Mensaje;
import edu.upb.chatupb_v2.model.entities.message.Message;
import edu.upb.chatupb_v2.controller.Mediador;
import edu.upb.chatupb_v2.model.repository.Chats;
import edu.upb.chatupb_v2.model.repository.Contact;
import lombok.Setter;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;


public class ChatView extends JFrame implements iChatView {
    private ChatUI chatUI;
    public String idUsuarioActual;

    private final String idMio = "kf3fc20a-766c-4rd4-813d-b1967a01fa9a";
    private final String nombre = "Irene";
    private DefaultListModel<Contact> contacModel = new DefaultListModel<>();

    @Setter
    public ContactController contactController;
    @Setter
    public ChatsController chatsController;

    public ChatView(ChatUI chatUI) {
        this.chatUI = chatUI;
        initComponents();
        this.jContactos.setCellRenderer(new ContactRenderer());
    }

    private ChatView() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jBtnEnviar = new JButton();
//        jtMensaje = new JTextField();
//        jTextPaneChat = new JTextPane();
//        jTextPaneChat.setEditable(false);
//
//        jScrollPaneChat = new JScrollPane();
//        jScrollPaneChat.setViewportView(jTextPaneChat);
//
//
//        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
//
//
//        jBtnEnviar.setText("Enviar");
//        jBtnEnviar.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jBtnEnviarActionPerformed(evt);
//            }
//        });
//
//        jBtnNuevaConexion = new JButton("+");
//        jBtnNuevaConexion.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jBtnNuevaConexionActionPerformed(evt);
//            }
//        });
//        jBtnOff = new JButton("off");
//        jBtnOff.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jBtnOffActionPerformed(evt);
//            }
//        });
//
//
//        GroupLayout layout = new GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addGap(20, 20, 20)
//                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addComponent(jScrollPaneChat, GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
//                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
//                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.CENTER)
//                                                        .addComponent(jBtnOff, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
//                                                        .addComponent(jBtnNuevaConexion, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addComponent(jtMensaje)
//                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
//                                                .addComponent(jBtnEnviar)))
//                                .addGap(20, 20, 20))
//        );
//        layout.setVerticalGroup(
//                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addGap(20, 20, 20)
//                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
//                                        .addComponent(jScrollPaneChat, GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addComponent(jBtnOff, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
//                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
//                                                .addComponent(jBtnNuevaConexion, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)))
//                                .addGap(18, 18, 18)
//                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jtMensaje, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jBtnEnviar))
//                                .addGap(20, 20, 20))
//        );
//
//        pack();
//    }

// </editor-fold>//GEN-END:initComponents
    private void initComponents() {

        // ===== COMPONENTES CHAT =====
        jtMensaje = new JTextField();
        jPanelChat = new JPanel();
        jPanelChat.setLayout(new BoxLayout(jPanelChat, BoxLayout.Y_AXIS));
        jPanelChat.setBackground(Color.WHITE);

        jScrollPaneChat = new JScrollPane(jPanelChat);
        jScrollPaneChat.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

        jContactos = new JList<>();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setSize(900, 600);
        setLocationRelativeTo(null);

        jBtnEnviar = new JButton("Enviar");
        jBtnEnviar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jBtnEnviarActionPerformed(evt);
            }
        });

        jBtnNuevaConexion = new JButton("+");
        jBtnNuevaConexion.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jBtnNuevaConexionActionPerformed(evt);
            }
        });

        jBtnOff = new JButton("off");
        jBtnOff.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jBtnOffActionPerformed(evt);
            }
        });

        // ===== PANEL PRINCIPAL =====
        setLayout(new BorderLayout());

        // PANEL IZQUIERDO (CONTACTOS)

        JPanel panelContactos = new JPanel(new BorderLayout());
        panelContactos.setPreferredSize(new Dimension(220, 0));
        panelContactos.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 1, Color.LIGHT_GRAY));

        JLabel lblContactos = new JLabel("Contactos", SwingConstants.CENTER);
        lblContactos.setFont(new Font("Arial", Font.BOLD, 14));
        lblContactos.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jContactos = new JList<>(contacModel);
        jContactos.setCellRenderer(new ContactRenderer());
        jContactos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

//        jContactos.addListSelectionListener(e -> {
//            if (!e.getValueIsAdjusting()) {
//                Contact seleccionado = jContactos.getSelectedValue();
//                if (seleccionado != null) {
//                    idUsuarioActual = String.valueOf(seleccionado.getId());
//                    limpiarChat();
//                    chatsController.onloadMessages(idMio, idUsuarioActual);
//                    System.out.println("Contacto seleccionado: " + seleccionado.getName());
//                    jPanelChat.revalidate();
//                    jPanelChat.repaint();
//                }
//            }
//        });
        jContactos.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {

                Contact seleccionado = jContactos.getSelectedValue();

                if (seleccionado != null && chatsController != null) {
                    idUsuarioActual = seleccionado.getId();
                    limpiarChat();
                    chatsController.onloadMessages(idMio, idUsuarioActual);
                    System.out.println("Cargando mensajes con: " + seleccionado.getName() + "con id:" + seleccionado.getId()) ;
                }
            }
        });

        JScrollPane scrollContactos = new JScrollPane(jContactos);
        scrollContactos.setBorder(null);

        panelContactos.add(lblContactos, BorderLayout.NORTH);
        panelContactos.add(scrollContactos, BorderLayout.CENTER);

        // PANEL DERECHO (CHAT)

        JPanel panelChat = new JPanel(new BorderLayout());

        // Panel superior (botones off y +)
        JPanel panelSuperior = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        panelSuperior.add(jBtnOff);
        panelSuperior.add(jBtnNuevaConexion);

        // Panel inferior (campo mensaje + enviar)
        JPanel panelInferior = new JPanel(new BorderLayout(10, 0));
        panelInferior.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelInferior.add(jtMensaje, BorderLayout.CENTER);
        panelInferior.add(jBtnEnviar, BorderLayout.EAST);

        panelChat.add(panelSuperior, BorderLayout.NORTH);
        panelChat.add(jScrollPaneChat, BorderLayout.CENTER);
        panelChat.add(panelInferior, BorderLayout.SOUTH);

        //AGREGAR AL FRAME
        add(panelContactos, BorderLayout.WEST);
        add(panelChat, BorderLayout.CENTER);

    }
    private void showOffPopup() {

        JDialog dialog = new JDialog(this, true);
        dialog.setSize(320, 300);
        dialog.setLocationRelativeTo(this);
        dialog.setUndecorated(true);
        dialog.setBackground(new Color(0,0,0,0));

        JPanel root = new JPanel(null);
        root.setOpaque(false);

        // ===== CARD =====
        JPanel card = new JPanel();
        card.setLayout(null);
        card.setBackground(Color.WHITE);
        card.setBounds(40, 90, 250, 110);
        card.setBorder(BorderFactory.createLineBorder(new Color(220,220,220), 1, true));

        // ===== TITULO =====
        JLabel title = new JLabel("Su conexión fue terminada");
        title.setFont(new Font("Arial", Font.BOLD, 16));
        title.setForeground(new Color(37,29,75));
        title.setHorizontalAlignment(SwingConstants.CENTER);
        title.setBounds(15, 20, 220, 30);

        // ===== BOTON OK =====
        JButton okButton = new JButton("Ok");
        okButton.setBounds(100, 60, 50, 30);
        okButton.setBackground(new Color(202,203,233));
        okButton.setFocusPainted(false);

        okButton.addActionListener(e -> dialog.dispose());

        card.add(title);
        card.add(okButton);

        // ===== IMAGEN =====
        JLabel imageLabel = new JLabel();
        imageLabel.setBounds(115, 0, 110, 110);

        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/robotOff.png"));
            Image img = icon.getImage().getScaledInstance(110, -1, Image.SCALE_SMOOTH);
            imageLabel.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            imageLabel.setText("Img");
        }

        root.add(card);
        root.add(imageLabel);

        dialog.add(root);
        dialog.setVisible(true);
    }
    private void showNoMessagePopup() {

        JDialog dialog = new JDialog(this, true);
        dialog.setSize(320, 300);
        dialog.setLocationRelativeTo(this);
        dialog.setUndecorated(true);
        dialog.setBackground(new Color(0,0,0,0));

        JPanel root = new JPanel(null);
        root.setOpaque(false);

        // ===== CARD =====
        JPanel card = new JPanel();
        card.setLayout(null);
        card.setBackground(Color.WHITE);
        card.setBounds(40, 90, 250, 110);
        card.setBorder(BorderFactory.createLineBorder(new Color(220,220,220), 1, true));

        // ===== TITULO =====
        JLabel title = new JLabel("No puede enviar mensajes");
        title.setFont(new Font("Arial", Font.BOLD, 16));
        title.setForeground(new Color(37,29,75));
        title.setHorizontalAlignment(SwingConstants.CENTER);
        title.setBounds(15, 20, 220, 30);

        // ===== BOTON OK =====
        JButton okButton = new JButton("Ok");
        okButton.setBounds(100, 60, 50, 30);
        okButton.setBackground(new Color(202,203,233));
        okButton.setFocusPainted(false);

        okButton.addActionListener(e -> dialog.dispose());

        card.add(title);
        card.add(okButton);

        // ===== IMAGEN =====
        JLabel imageLabel = new JLabel();
        imageLabel.setBounds(115, 0, 110, 110);

        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/robotNoMessage.png"));
            Image img = icon.getImage().getScaledInstance(110, -1, Image.SCALE_SMOOTH);
            imageLabel.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            imageLabel.setText("Img");
        }

        root.add(card);
        root.add(imageLabel);

        dialog.add(root);
        dialog.setVisible(true);
    }
    private void jBtnEnviarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jBtnEnviarActionPerformed
        String mensajeTxt = jtMensaje.getText().toString();
        if (mensajeTxt.isEmpty() || idUsuarioActual == null) {
            System.out.println("Entra aca");
            return;
        }

        System.out.println("Enviando 007...");
        Mediador.getInstance().enviarMensajePorChat(idUsuarioActual, mensajeTxt);
        jtMensaje.setText("");

//    }else {
//            showNoMessagePopup();
//        }
    }//GEN-LAST:event_jBtnEnviarActionPerformed
    private void jBtnOffActionPerformed(ActionEvent evt) {
//        if (client.isAlive()) {
            try {
                System.out.println("Enviando 0018...");
                System.out.println("Conexion terminada");
                Message message = new FueraLinea(idMio);
                Mediador.getInstance().enviarMensajeATodos(message);
                mostrarMensajeSistema("CONEXION TERMINADA");
            } catch (Exception e) {
                e.printStackTrace();
            }
//        }
    }
    private void jBtnNuevaConexionActionPerformed(ActionEvent evt) {
        chatUI.setVisible(true);
    }
//    public void agregarMensaje(String texto, boolean esMio) {
//        StyledDocument doc = jTextPaneChat.getStyledDocument();
//        SimpleAttributeSet attrs = new SimpleAttributeSet();
//
//        if (esMio) {
//            StyleConstants.setAlignment(attrs, StyleConstants.ALIGN_RIGHT);
//            StyleConstants.setForeground(attrs, Color.BLUE);
//        } else {
//            StyleConstants.setAlignment(attrs, StyleConstants.ALIGN_LEFT);
//            StyleConstants.setForeground(attrs, Color.BLACK);
//        }
//
//        try {
//            int len = doc.getLength();
//            doc.insertString(len, texto + "\n", attrs);
//            doc.setParagraphAttributes(len, texto.length(), attrs, false);
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }
    public void agregarContacto(Contact contact) {
        if (contact == null || contact.getId() == null) {
            System.out.println("Contacto inválido");
            return;
        }

        for (int i = 0; i < contacModel.size(); i++) {
            System.out.println("contacModel.get(i).getId(): " + contacModel.get(i).getId());
            System.out.println("idCliente: (ChatView) " + contact.getId());
            if (contacModel.get(i).getId().equals(contact.getId())) {
                return;
            }
        }
        System.out.println("nombreCliente: (ChatView) " + contact.getName());
        System.out.println("ip: (ChatView)" + contact.getIp());
        contacModel.addElement(contact);
        System.out.println("Agregando contacto con id al conctacModel: (ChatView)" + contact.getId());
    }
//    public void mostrarMensajeSistema(String texto) {
//        StyledDocument doc = jTextPaneChat.getStyledDocument();
//        SimpleAttributeSet attrs = new SimpleAttributeSet();
//
//        StyleConstants.setAlignment(attrs, StyleConstants.ALIGN_CENTER);
//        StyleConstants.setBold(attrs, true);
//        StyleConstants.setForeground(attrs, Color.RED);
//
//        try {
//            int len = doc.getLength();
//            doc.insertString(len, texto + "\n", attrs);
//            doc.setParagraphAttributes(len, texto.length(), attrs, false);
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }
    public void mostrarMensajeSistema(String texto) {

        JPanel panelSistema = new JPanel(new FlowLayout(FlowLayout.CENTER));
        panelSistema.setOpaque(false);

        JLabel lblSistema = new JLabel(texto);
        lblSistema.setForeground(Color.RED);
        lblSistema.setFont(new Font("Arial", Font.BOLD, 12));

        panelSistema.add(lblSistema);

        jPanelChat.add(panelSistema);
        jPanelChat.revalidate();
        jPanelChat.repaint();
    }
    public void actualizarValores(String idUsuarioActual) {
        this.idUsuarioActual = idUsuarioActual;
    }

    public String obtenerHoraActual() {
        java.time.LocalTime hora = java.time.LocalTime.now();
        java.time.format.DateTimeFormatter formatter =
                java.time.format.DateTimeFormatter.ofPattern("HH:mm");
        return hora.format(formatter);
    }
    private JPanel crearBurbuja(String texto, boolean esMio, String hora) {

        JPanel bubble = new JPanel(new BorderLayout());
        bubble.setBorder(BorderFactory.createEmptyBorder(8, 12, 8, 12));
        bubble.setOpaque(true);

        if (esMio) {
            bubble.setBackground(new Color(173,216,230));
        } else {
            bubble.setBackground(new Color(230,230,230));
        }

        JLabel lblTexto = new JLabel(
                "<html><div style='max-width:250px;'>" + texto + "</div></html>"
        );
        JLabel lblHora = new JLabel(hora);
        lblHora.setFont(new Font("Arial", Font.PLAIN, 9));
        lblHora.setForeground(Color.DARK_GRAY);
        lblHora.setHorizontalAlignment(SwingConstants.RIGHT);

        bubble.add(lblTexto, BorderLayout.CENTER);
        bubble.add(lblHora, BorderLayout.SOUTH);

        return bubble;
    }
    private JLabel crearFotoPerfil() {

        JLabel foto = new JLabel();

        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/user.png"));
            Image img = icon.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
            foto.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            foto.setText("");
        }

        return foto;
    }
    private JPanel crearFilaMensaje(String texto, boolean esMio) {

        JPanel fila = new JPanel(new FlowLayout(
                esMio ? FlowLayout.RIGHT : FlowLayout.LEFT
        ));
        fila.setOpaque(false);
        fila.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));

        JPanel bubble = crearBurbuja(texto, esMio, obtenerHoraActual());

        if (!esMio) {
            fila.add(crearFotoPerfil());
        }

        fila.add(bubble);

        return fila;
    }
    public void agregarMensaje(String texto, boolean esMio, String hora) {

        JPanel mensaje = crearFilaMensaje(texto, esMio);

        jPanelChat.add(mensaje);
        jPanelChat.revalidate();
        jPanelChat.repaint();

        SwingUtilities.invokeLater(() -> {
            JScrollBar vertical = jScrollPaneChat.getVerticalScrollBar();
            vertical.setValue(vertical.getMaximum());
        });
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChatView().setVisible(true);
//            }
//        });
//    }

//     Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jBtnEnviar;
    private JTextField jtMensaje;
    private JPanel jPanelChat;
    private JScrollPane jScrollPaneChat;
    private JButton jBtnNuevaConexion;
    private JButton jBtnOff;
    private JList<Contact> jContactos;

    public void onMessage(Message message) {
        if (message instanceof Mensaje) {
            Mensaje mensaje = (Mensaje) message;
            agregarMensaje(mensaje.getMensaje(), false, obtenerHoraActual());
            chatsController.guardarEnBd(mensaje.getIdMensaje(), mensaje.getMensaje(), mensaje.getIdUsuario(), idMio, obtenerHoraActual());
            System.out.print("Llegó el mensaje: " + mensaje + '\n');
        }
        if (message instanceof FueraLinea) {
            System.out.println("Conexión terminada por cliente");
            showOffPopup();
            mostrarMensajeSistema("CONEXION TERMINADA");
            Mediador.getInstance().removeClient(idUsuarioActual);
        }
        if (message instanceof Hello) {
//            Mediador.getInstance().establecerConexion(message.ge);
        }
    }
    private void limpiarChat() {
        jPanelChat.removeAll();
        jPanelChat.revalidate();
        jPanelChat.repaint();
    }

    @Override
    public void onloadContacts(List<Contact> contacts) {
        try {
            if (contacts.isEmpty())
                System.out.println("BD vacia");
            contacModel.addAll(contacts);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void onloadMessages(List<Chats> chats) {
        limpiarChat();
        for (Chats c : chats) {
            boolean emisor = c.getIdEmisor().equals(idMio);
            agregarMensaje(c.getMensajeTxt(), emisor, c.getHora());
        }
    }
    // End of variables declaration//GEN-END:variables
}