/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upb.chatupb_v2.view;

import edu.upb.chatupb_v2.controller.ChatsController;
import edu.upb.chatupb_v2.controller.ContactController;
import edu.upb.chatupb_v2.model.entities.message.*;
import edu.upb.chatupb_v2.controller.Mediador;
import lombok.Setter;

import javax.swing.*;
import javax.swing.border.AbstractBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;


public class ChatUI extends JFrame implements iChatView {
    public String idUsuarioActual;
    private DefaultListModel<Contact> contacModel = new DefaultListModel<>();

    private static final Color BG_DARK       = new Color(15, 20, 35);
    private static final Color BG_PANEL      = new Color(22, 28, 48);
    private static final Color BG_SIDEBAR    = new Color(18, 24, 42);
    private static final Color BG_INPUT      = new Color(30, 38, 62);
    private static final Color BG_BUBBLE_ME  = new Color(79, 70, 229);
    private static final Color BG_BUBBLE_YOU = new Color(36, 44, 70);
    private static final Color ACCENT        = new Color(129, 140, 248);
    private static final Color ACCENT_HOVER  = new Color(165, 180, 252);
    private static final Color TEXT_PRIMARY  = new Color(240, 242, 255);
    private static final Color TEXT_MUTED    = new Color(148, 163, 184);
    private static final Color DIVIDER       = new Color(255, 255, 255, 18);
    private static final Color BTN_SEND      = new Color(99, 102, 241);
    private static final Color BTN_SEND_HOV  = new Color(129, 140, 248);
    private static final Color SYSTEM_RED    = new Color(248, 113, 113);

    @Setter
    public ContactController contactController;
    @Setter
    public ChatsController chatsController;

    public ChatUI() {

        initComponents();
        this.jContactos.setCellRenderer(new ContactRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

// </editor-fold>//GEN-END:initComponents
    private void initComponents() {

        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }

        // ===== COMPONENTES CHAT =====
        jtMensaje = new JTextField();
        jPanelChat = new JPanel();
        jPanelChat.setLayout(new BoxLayout(jPanelChat, BoxLayout.Y_AXIS));
        jPanelChat.setBackground(BG_PANEL);

        jScrollPaneChat = new JScrollPane(jPanelChat);
        jScrollPaneChat.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

        jScrollPaneChat.setBorder(null);
        jScrollPaneChat.getViewport().setBackground(BG_PANEL);
        styleScrollBar(jScrollPaneChat, new Color(79, 70, 229, 100));

        jContactos = new JList<>();
        jPopupMenu = new JPopupMenu();
        stylePopupMenu(jPopupMenu);

        itemHello = createMenuItem("Enviar hello");
        itemZumbido = createMenuItem("Enviar Zumbido");
        itemInvitacion = createMenuItem("Enviar invitacion");
        itemEnviarContacto = createMenuItem("Enviar contacto");
        itemActualizarIp = createMenuItem("Actualizar Ip");
        jPopupMenu.add(itemHello);
        jPopupMenu.add(itemZumbido);
        jPopupMenu.add(itemInvitacion);
        jPopupMenu.add(itemEnviarContacto);
        jPopupMenu.add(itemActualizarIp);

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setSize(900, 600);
        setLocationRelativeTo(null);
        setBackground(BG_DARK);

        jBtnEnviar = createSendButton();
        jBtnEnviar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jBtnEnviarActionPerformed(evt);
            }
        });

        jBtnNuevaConexion = createIconButton("+", "Agregar contacto");
        jBtnNuevaConexion.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jBtnNuevaConexionActionPerformed(evt);
            }
        });

        jBtnOff = createDangerButton("⏻");
        jBtnOff.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jBtnOffActionPerformed(evt);
            }
        });


        // ===== LAYOUT PRINCIPAL =====
        setLayout(new BorderLayout());
        getContentPane().setBackground(BG_DARK);

        // ─── SIDEBAR IZQUIERDO ───
        JPanel panelContactos = new JPanel(new BorderLayout());
        panelContactos.setPreferredSize(new Dimension(240, 0));
        panelContactos.setBackground(BG_SIDEBAR);
        panelContactos.setBorder(BorderFactory.createMatteBorder(
                0, 0, 0, 1, new Color(255, 255, 255, 18)));

        // Header del sidebar
        JPanel sidebarHeader = new JPanel(new BorderLayout());
        sidebarHeader.setBackground(BG_SIDEBAR);
        sidebarHeader.setBorder(BorderFactory.createEmptyBorder(20, 16, 12, 16));

        JLabel lblContactos = new JLabel("Contactos");
        lblContactos.setFont(new Font("Georgia", Font.BOLD, 17));
        lblContactos.setForeground(TEXT_PRIMARY);

        sidebarHeader.setBorder(BorderFactory.createEmptyBorder(14, 16, 14, 16));

        sidebarHeader.add(lblContactos, BorderLayout.WEST);
        sidebarHeader.add(buildSidebarDivider(), BorderLayout.SOUTH);

        lblContactoSeleccionado = new JLabel("ChatUPB");
        // Lista de contactos
        jContactos = new JList<>(contacModel);
        jContactos.setCellRenderer(new ContactRenderer());
        jContactos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jContactos.setFixedCellHeight(58);
        jContactos.setBackground(BG_SIDEBAR);
        jContactos.setBorder(BorderFactory.createEmptyBorder(4, 0, 4, 0));
        jContactos.setSelectionBackground(new Color(79, 70, 229, 60));
        jContactos.setSelectionForeground(TEXT_PRIMARY);

        jContactos.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                Contact seleccionado = jContactos.getSelectedValue();
                if (seleccionado != null && chatsController != null) {
                    lblContactoSeleccionado.setText(seleccionado.getName());
                    seleccionado.setMensajesNoLeidos(false);
                    seleccionado.setZumbido(false);
                    jContactos.repaint();
                    idUsuarioActual = seleccionado.getId();
                    limpiarChat();
                    chatsController.onloadMessages(Mediador.getInstance().getIdMio(), idUsuarioActual);
                }
            }
        });

        jContactos.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseMoved(MouseEvent e) {
                int index = jContactos.locationToIndex(e.getPoint());
                if (index != -1) {
                    Rectangle cellBounds = jContactos.getCellBounds(index, index);
                    if (cellBounds != null && cellBounds.contains(e.getPoint())) {
                        ((ContactRenderer) jContactos.getCellRenderer()).setHoverIndex(index);
                    } else {
                        ((ContactRenderer) jContactos.getCellRenderer()).setHoverIndex(-1);
                    }
                } else {
                    ((ContactRenderer) jContactos.getCellRenderer()).setHoverIndex(-1);
                }
                jContactos.repaint();
            }
        });

        jContactos.addMouseListener(new MouseAdapter() {
            private void mostrarMenu(MouseEvent e) {
                if (SwingUtilities.isRightMouseButton(e)) {
                    int pos = jContactos.locationToIndex(e.getPoint());
                    if (pos != -1) {
                        Rectangle cellBounds = jContactos.getCellBounds(pos, pos);
                        if (cellBounds != null && cellBounds.contains(e.getPoint())) {
                            jContactos.setSelectedIndex(pos);
                            jPopupMenu.show(jContactos, e.getX(), e.getY());
                        }
                    }
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
                int index = jContactos.locationToIndex(e.getPoint());
                if (index != -1) {
                    Rectangle cellBounds = jContactos.getCellBounds(index, index);
                    if (cellBounds == null || !cellBounds.contains(e.getPoint())) {
                        jContactos.clearSelection();
                        limpiarChat();
                        idUsuarioActual = null;
                        lblContactoSeleccionado.setText("ChatUPB");
                    }
                }
                mostrarMenu(e);
            }
//            @Override
//            public void mouseClicked(MouseEvent e) {
//                if (SwingUtilities.isRightMouseButton(e)) {
//                    System.out.println("click derecho");
//                }
//            }
            @Override
            public void mouseReleased(MouseEvent e) {
                mostrarMenu(e);
            }
            @Override
            public void mouseExited(MouseEvent e) {
                ((ContactRenderer) jContactos.getCellRenderer()).setHoverIndex(-1);
                jContactos.repaint();
            }

        });

        itemHello.addActionListener(e -> {
            Contact seleccionado = jContactos.getSelectedValue();
            if (seleccionado != null && chatsController != null) {
                idUsuarioActual = seleccionado.getId();
                Mediador.getInstance().enviarHello(idUsuarioActual);
            }
        });
        itemZumbido.addActionListener(e -> {
            Contact seleccionado = jContactos.getSelectedValue();
            if (seleccionado != null) {
                idUsuarioActual = seleccionado.getId();
                Zumbido zumbido = new Zumbido(Mediador.getInstance().getIdMio());
                Mediador.getInstance().sendMessage(idUsuarioActual, zumbido);
            }
        });
        itemEnviarContacto.addActionListener(e -> {
            showEnviarContactoPopup();
        });
        itemInvitacion.addActionListener(e -> {
            Contact seleccionado = jContactos.getSelectedValue();
            if (seleccionado != null) {
                idUsuarioActual = seleccionado.getId();
                Mediador.getInstance().establecerConexion(seleccionado.getIp());
            }
        });
        itemActualizarIp.addActionListener(e -> {
            Contact seleccionado = jContactos.getSelectedValue();
            if (seleccionado != null) {
                idUsuarioActual = seleccionado.getId();
                showIpPopup();
            }
        });

        JScrollPane scrollContactos = new JScrollPane(jContactos);
        scrollContactos.setBorder(null);
        scrollContactos.getViewport().setBackground(BG_SIDEBAR);
        styleScrollBar(scrollContactos, new Color(100, 100, 100, 80));

//        panelContactos.add(lblContactos, BorderLayout.NORTH);
//        panelContactos.add(scrollContactos, BorderLayout.CENTER);
        panelContactos.add(sidebarHeader, BorderLayout.NORTH);
        panelContactos.add(scrollContactos, BorderLayout.CENTER);

        // PANEL DERECHO (CHAT)
        JPanel panelChat = new JPanel(new BorderLayout());
        panelChat.setBackground(BG_PANEL);

        // Panel superior (botones off y +)
        JPanel panelSuperior = new JPanel(new BorderLayout());
        panelSuperior.setBackground(BG_SIDEBAR);
        panelSuperior.setBorder(BorderFactory.createEmptyBorder(12, 20, 12, 16));

        lblContactoSeleccionado.setFont(new Font("Georgia", Font.BOLD, 15));
        lblContactoSeleccionado.setForeground(ACCENT);
        panelSuperior.add(lblContactoSeleccionado, BorderLayout.WEST);

        JPanel botonesHeader = new JPanel(new FlowLayout(FlowLayout.RIGHT, 8, 0));
        botonesHeader.setOpaque(false);
        botonesHeader.add(jBtnOff);
        botonesHeader.add(jBtnNuevaConexion);
        panelSuperior.add(botonesHeader, BorderLayout.EAST);

        JSeparator sep = new JSeparator();
        sep.setForeground(DIVIDER);
        sep.setBackground(BG_SIDEBAR);
        panelSuperior.add(sep, BorderLayout.SOUTH);

        // Panel inferior (campo mensaje + enviar)
        JPanel panelInferior = buildInputPanel();

        panelChat.add(panelSuperior, BorderLayout.NORTH);
        panelChat.add(jScrollPaneChat, BorderLayout.CENTER);
        panelChat.add(panelInferior, BorderLayout.SOUTH);

        add(panelContactos, BorderLayout.WEST);
        add(panelChat, BorderLayout.CENTER);

        // ── BANNER MENSAJE FIJADO (nuevo) ──
        panelMensajeFijado = new JPanel(new BorderLayout());
        panelMensajeFijado.setBackground(new Color(45, 38, 90));
        panelMensajeFijado.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(79, 70, 229, 80)),
                BorderFactory.createEmptyBorder(7, 16, 7, 16)
        ));
        panelMensajeFijado.setVisible(false);

        JLabel iconPin = new JLabel("📌");
        iconPin.setFont(new Font("Segoe UI Emoji", Font.PLAIN, 13));
        iconPin.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 8));

        lblMensajeFijado = new JLabel("Mensaje fijado");
        lblMensajeFijado.setForeground(ACCENT);
        lblMensajeFijado.setFont(new Font("Segoe UI", Font.PLAIN, 12));

        JButton btnDesfijar = new JButton("✕");
        btnDesfijar.setFont(new Font("Segoe UI", Font.PLAIN, 11));
        btnDesfijar.setForeground(TEXT_MUTED);
        btnDesfijar.setContentAreaFilled(false);
        btnDesfijar.setBorderPainted(false);
        btnDesfijar.setFocusPainted(false);
        btnDesfijar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnDesfijar.addActionListener(e -> desfijarMensaje());

        JPanel pinLeft = new JPanel(new FlowLayout(FlowLayout.LEFT, 0, 0));
        pinLeft.setOpaque(false);
        pinLeft.add(iconPin);
        pinLeft.add(lblMensajeFijado);

        panelMensajeFijado.add(pinLeft, BorderLayout.WEST);
        panelMensajeFijado.add(btnDesfijar, BorderLayout.EAST);

// Armar panel norte (header + pin banner)
        JPanel panelNorte = new JPanel(new BorderLayout());
        panelNorte.add(panelSuperior, BorderLayout.NORTH);
        panelNorte.add(panelMensajeFijado, BorderLayout.SOUTH);

        panelChat.add(panelNorte, BorderLayout.NORTH);
        panelChat.add(jScrollPaneChat, BorderLayout.CENTER);
        panelChat.add(panelInferior, BorderLayout.SOUTH);

        if (Mediador.getInstance().dbVacia()) {
            showNombrePopup();
        }
        Mediador.getInstance().cargarMisDatos();
    }

    private JPanel buildSidebarDivider() {
        JPanel d = new JPanel();
        d.setPreferredSize(new Dimension(0, 1));
        d.setBackground(new Color(255, 255, 255, 15));
        return d;
    }
    private JPanel buildInputPanel() {
        JPanel panelInferior = new JPanel(new BorderLayout(10, 0));
        panelInferior.setBackground(BG_SIDEBAR);
        panelInferior.setBorder(BorderFactory.createEmptyBorder(14, 16, 14, 16));

        // Campo de texto estilizado
        jtMensaje = new JTextField();
        jtMensaje.setBackground(BG_INPUT);
        jtMensaje.setForeground(TEXT_PRIMARY);
        jtMensaje.setCaretColor(ACCENT);
        jtMensaje.setBorder(BorderFactory.createEmptyBorder(10, 16, 10, 16));
        jtMensaje.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        jtMensaje.putClientProperty("JTextField.placeholderText", "Escribe un mensaje...");

        // Acción de Enter
        jtMensaje.addActionListener(evt -> jBtnEnviarActionPerformed(evt));

        panelInferior.add(jtMensaje, BorderLayout.CENTER);
        panelInferior.add(jBtnEnviar, BorderLayout.EAST);

        return panelInferior;
    }
    private JButton createSendButton() {
        JButton btn = new JButton("➤") {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                Color bg = getModel().isRollover() ? BTN_SEND_HOV : BTN_SEND;
                g2.setColor(bg);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 22, 22);
                g2.dispose();
                super.paintComponent(g);
            }
        };
        btn.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        btn.setForeground(Color.WHITE);
//        btn.setPreferredSize(new Dimension(68, 44));
        btn.setMargin(new Insets(8, 20, 8, 20));
        btn.setContentAreaFilled(false);
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        return btn;
    }
    private JButton createIconButton(String text, String tooltip) {
        JButton btn = new JButton(text) {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                Color bg = getModel().isRollover()
                        ? new Color(79, 70, 229, 80)
                        : new Color(79, 70, 229, 35);
                g2.setColor(bg);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 12, 12);
                g2.dispose();
                super.paintComponent(g);
            }
        };
        btn.setFont(new Font("Segoe UI", Font.BOLD, 18));
        btn.setForeground(ACCENT);
//        btn.setPreferredSize(new Dimension(36, 32));
        btn.setMargin(new Insets(4, 20, 4, 20));
        btn.setContentAreaFilled(false);
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn.setToolTipText(tooltip);
        return btn;
    }
    private JButton createDangerButton(String text) {
        JButton btn = new JButton(text) {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                Color bg = getModel().isRollover()
                        ? new Color(239, 68, 68, 90)
                        : new Color(239, 68, 68, 35);
                g2.setColor(bg);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 12, 12);
                g2.dispose();
                super.paintComponent(g);
            }
        };
        btn.setFont(new Font("Segoe UI Emoji", Font.PLAIN, 16));
        btn.setForeground(new Color(248, 113, 113));
//        btn.setPreferredSize(new Dimension(36, 32));
        btn.setMargin(new Insets(4, 20, 4, 20));
        btn.setContentAreaFilled(false);
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn.setToolTipText("Desconectarse");
        return btn;
    }
    private void styleScrollBar(JScrollPane sp, Color color) {
        JScrollBar vsb = sp.getVerticalScrollBar();
        vsb.setUI(new javax.swing.plaf.basic.BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                thumbColor = color;
                trackColor = new Color(0, 0, 0, 0);
            }
            @Override
            protected JButton createDecreaseButton(int o) { return zeroButton(); }
            @Override
            protected JButton createIncreaseButton(int o) { return zeroButton(); }
            private JButton zeroButton() {
                JButton b = new JButton();
                b.setPreferredSize(new Dimension(0, 0));
                return b;
            }
            @Override
            protected void paintThumb(Graphics g, JComponent c, Rectangle r) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(thumbColor);
                g2.fillRoundRect(r.x + 2, r.y + 2, r.width - 4, r.height - 4, 8, 8);
                g2.dispose();
            }
        });
        vsb.setPreferredSize(new Dimension(6, 0));
    }
    private void stylePopupMenu(JPopupMenu menu) {
        menu.setBackground(new Color(26, 32, 54));
        menu.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(79, 70, 229, 80), 1),
                BorderFactory.createEmptyBorder(4, 0, 4, 0)
        ));
    }
    private JMenuItem createMenuItem(String text) {
        JMenuItem item = new JMenuItem(text);
        item.setBackground(new Color(26, 32, 54));
        item.setForeground(TEXT_PRIMARY);
        item.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        item.setBorder(BorderFactory.createEmptyBorder(7, 16, 7, 16));
        item.setOpaque(true);
        return item;
    }

    private JDialog createBaseDialog(int w, int h) {
        JDialog dialog = new JDialog(this, true);
        dialog.setSize(w, h);
        dialog.setLocationRelativeTo(this);
        dialog.setUndecorated(true);
        dialog.setBackground(new Color(0, 0, 0, 0));
        return dialog;
    }
    private JPanel createDarkCard(int x, int y, int w, int h) {
        JPanel card = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(BG_PANEL);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
                g2.setColor(new Color(79, 70, 229, 60));
                g2.setStroke(new BasicStroke(1f));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 20, 20);
                g2.dispose();
            }
        };
        card.setLayout(null);
        card.setOpaque(false);
        card.setBounds(x, y, w, h);
        return card;
    }
    private JButton createPopupOkButton(String text, int x, int y, int w, int h) {
        JButton btn = new JButton(text) {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                Color bg = getModel().isRollover() ? BTN_SEND_HOV : BTN_SEND;
                g2.setColor(bg);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 12, 12);
                g2.dispose();
                super.paintComponent(g);
            }
        };
        btn.setBounds(x, y, w, h);
        btn.setForeground(Color.WHITE);
        btn.setFont(new Font("Segoe UI", Font.BOLD, 13));
        btn.setContentAreaFilled(false);
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        return btn;
    }
    private JTextField createDarkTextField(int x, int y, int w, int h) {
        JTextField tf = new JTextField();
        tf.setBounds(x, y, w, h);
        tf.setBackground(BG_INPUT);
        tf.setForeground(TEXT_PRIMARY);
        tf.setCaretColor(ACCENT);
        tf.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        tf.setBorder(BorderFactory.createEmptyBorder(6, 12, 6, 12));
        return tf;
    }
    private JLabel createRobotIcon(int x, int y, String imagePath) {
        JLabel lbl = new JLabel();
        lbl.setBounds(x, y, 90, 120);
        lbl.setHorizontalAlignment(SwingConstants.CENTER);
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
            Image img = icon.getImage().getScaledInstance(90, -1, Image.SCALE_SMOOTH);
            lbl.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            lbl.setText("🤖");
            lbl.setFont(new Font("Segoe UI Emoji", Font.PLAIN, 40));
        }
        return lbl;
    }

    private void showOffPopup() {
        JDialog dialog = createBaseDialog(360, 240);
        JPanel root = new JPanel(null); root.setOpaque(false);

        JPanel card = createDarkCard(20, 30, 320, 170);

        JLabel robot = createRobotIcon(230, -20, "/images/robotOff.png");
        JLabel title = new JLabel("Conexión terminada");
        title.setFont(new Font("Georgia", Font.BOLD, 16));
        title.setForeground(TEXT_PRIMARY);
        title.setBounds(20, 30, 200, 28);

        JLabel sub = new JLabel("Tu sesión fue cerrada.");
        sub.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        sub.setForeground(TEXT_MUTED);
        sub.setBounds(20, 62, 200, 20);

        JButton ok = createPopupOkButton("Aceptar", 20, 110, 100, 34);
        ok.addActionListener(e -> dialog.dispose());

        card.add(title); card.add(sub); card.add(ok);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }
    private void showAcceptPopup() {
        JDialog dialog = createBaseDialog(340, 220);
        JPanel root = new JPanel(null); root.setOpaque(false);

        JPanel card = createDarkCard(20, 30, 300, 160);

        JLabel robot = createRobotIcon(210, -15, "/images/robotAccept.png");
        JLabel title = new JLabel("¡Conexión aceptada!");
        title.setFont(new Font("Georgia", Font.BOLD, 16));
        title.setForeground(TEXT_PRIMARY);
        title.setBounds(20, 30, 200, 28);

        JButton ok = createPopupOkButton("OK", 20, 100, 90, 34);
        ok.addActionListener(e -> dialog.dispose());

        card.add(title); card.add(ok);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }
    private void showDeclinePopup() {
        JDialog dialog = createBaseDialog(340, 220);
        JPanel root = new JPanel(null); root.setOpaque(false);

        JPanel card = createDarkCard(20, 30, 300, 160);

        JLabel robot = createRobotIcon(210, -15, "/images/robotDecline.png");
        JLabel title = new JLabel("Conexión rechazada");
        title.setFont(new Font("Georgia", Font.BOLD, 16));
        title.setForeground(TEXT_PRIMARY);
        title.setBounds(20, 30, 200, 28);

        JButton ok = createPopupOkButton("OK", 20, 100, 90, 34);
        ok.addActionListener(e -> dialog.dispose());

        card.add(title); card.add(ok);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }
    public void showZumbidoPopup(String nombre) {
        JDialog dialog = createBaseDialog(360, 230);
        JPanel root = new JPanel(null); root.setOpaque(false);

        JPanel card = createDarkCard(20, 30, 320, 170);

        JLabel robot = createRobotIcon(230, -15, "/images/robotAccept.png");
        JLabel title = new JLabel("🔔 " + nombre + " te zumbó");
        title.setFont(new Font("Georgia", Font.BOLD, 15));
        title.setForeground(new Color(251, 191, 36));
        title.setBounds(20, 30, 230, 28);

        JButton ok = createPopupOkButton("OK", 20, 110, 90, 34);
        ok.addActionListener(e -> dialog.dispose());

        card.add(title); card.add(ok);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }
    public boolean showInvitationPopup(String nombreContacto) {
        final boolean[] accepted = {false};
        JDialog dialog = createBaseDialog(400, 270);
        JPanel root = new JPanel(null); root.setOpaque(false);
        JPanel card = createDarkCard(20, 40, 360, 200);
        JLabel robot = createRobotIcon(260, -10, "/images/robotRequest.png");

        JLabel title = new JLabel("Invitación de conexión");
        title.setFont(new Font("Georgia", Font.BOLD, 16));
        title.setForeground(TEXT_PRIMARY);
        title.setBounds(20, 20, 240, 28);

        JLabel sub = new JLabel("<html><body style='color:#94a3b8;font-size:12px;'>" + nombreContacto + " quiere conectarse</body></html>");
        sub.setBounds(20, 54, 240, 24);

        JButton accept = createPopupOkButton("Aceptar", 20, 140, 110, 36);
        accept.addActionListener(e -> {
            accepted[0] = true;
            dialog.dispose();
        });

        JButton decline = new JButton("Rechazar") {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(getModel().isRollover() ? new Color(239, 68, 68, 80) : new Color(239, 68, 68, 35));
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 12, 12);
                g2.dispose();
                super.paintComponent(g);
            }
        };
        decline.setBounds(148, 140, 110, 36);
        decline.setForeground(SYSTEM_RED);
        decline.setFont(new Font("Segoe UI", Font.BOLD, 13));
        decline.setContentAreaFilled(false);
        decline.setBorderPainted(false);
        decline.setFocusPainted(false);
        decline.setCursor(new Cursor(Cursor.HAND_CURSOR));
        decline.addActionListener(e -> { accepted[0] = false; dialog.dispose(); });

        card.add(title); card.add(sub); card.add(accept); card.add(decline);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
        return accepted[0];
    }
    public boolean showEliminarMensajePopup() {
        final boolean[] accepted = {false};
        JDialog dialog = createBaseDialog(400, 270);
        JPanel root = new JPanel(null); root.setOpaque(false);
        JPanel card = createDarkCard(20, 40, 360, 150);
        JLabel robot = createRobotIcon(260, -10, "/images/robotRequest.png");

        JLabel title = new JLabel("<html><div style='text-align:left;'>¿Seguro que desea eliminar el mensaje?</div></html>");
        title.setFont(new Font("Georgia", Font.BOLD, 16));
        title.setForeground(TEXT_PRIMARY);
        title.setBounds(20, 20, 310, 60); 

        JButton accept = createPopupOkButton("Si", 20, 90, 110, 36);
        accept.addActionListener(e -> {
            accepted[0] = true;
            dialog.dispose();
        });

        JButton decline = new JButton("No") {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(getModel().isRollover() ? new Color(239, 68, 68, 80) : new Color(239, 68, 68, 35));
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 12, 12);
                g2.dispose();
                super.paintComponent(g);
            }
        };
        decline.setBounds(148, 90, 110, 36);
        decline.setForeground(SYSTEM_RED);
        decline.setFont(new Font("Segoe UI", Font.BOLD, 13));
        decline.setContentAreaFilled(false);
        decline.setBorderPainted(false);
        decline.setFocusPainted(false);
        decline.setCursor(new Cursor(Cursor.HAND_CURSOR));
        decline.addActionListener(e -> { accepted[0] = false; dialog.dispose(); });

        card.add(title); card.add(accept); card.add(decline);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
        return accepted[0];
    }
    private void showNoMessagePopup() {
        JDialog dialog = createBaseDialog(340, 200);
        JPanel root = new JPanel(null); root.setOpaque(false);

        JPanel card = createDarkCard(20, 25, 300, 150);
        JLabel robot = createRobotIcon(210, -15, "/images/robotNoMessage.png");

        JLabel title = new JLabel("Sin destinatario");
        title.setFont(new Font("Georgia", Font.BOLD, 15));
        title.setForeground(new Color(251, 191, 36));
        title.setBounds(20, 25, 200, 28);

        JLabel sub = new JLabel("Selecciona un contacto primero.");
        sub.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        sub.setForeground(TEXT_MUTED);
        sub.setBounds(20, 56, 220, 20);

        JButton ok = createPopupOkButton("OK", 20, 98, 90, 34);
        ok.addActionListener(e -> dialog.dispose());

        card.add(title); card.add(sub); card.add(ok);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }
    private void showNuevaConexionPopup() {
        JDialog dialog = createBaseDialog(420, 310);
        JPanel root = new JPanel(null); root.setOpaque(false);

        JPanel card = createDarkCard(20, 40, 380, 250);
        JLabel robot = createRobotIcon(280, -10, "/images/robotAdd.png");

        JButton btnCerrar = new JButton();

        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/x1.png"));
            Image img = icon.getImage().getScaledInstance(40, 30, Image.SCALE_SMOOTH);
            btnCerrar.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            btnCerrar.setText("X");
        }

        btnCerrar.setBounds(340, 12, 25, 25);
        btnCerrar.setForeground(TEXT_MUTED);
        btnCerrar.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setFocusPainted(false);
        btnCerrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCerrar.addActionListener(e -> dialog.dispose());

        JLabel title = new JLabel("Agregar Contacto");
        title.setFont(new Font("Georgia", Font.BOLD, 18));
        title.setForeground(TEXT_PRIMARY);
        title.setBounds(24, 24, 240, 30);

        JLabel lbl = new JLabel("IP del contacto:");
        lbl.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        lbl.setForeground(TEXT_MUTED);
        lbl.setBounds(24, 76, 200, 20);

        jtIp = createDarkTextField(24, 100, 330, 40);

        jBtnConectar = createPopupOkButton("Conectar", 24, 162, 140, 38);
        jBtnConectar.addActionListener(evt -> {
            Mediador.getInstance().establecerConexion(jtIp.getText());
            dialog.dispose();
        });

        card.add(btnCerrar); card.add(title); card.add(lbl); card.add(jtIp); card.add(jBtnConectar);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }
    public void showNombrePopup() {
        JDialog dialog = createBaseDialog(420, 310);
        JPanel root = new JPanel(null); root.setOpaque(false);

        JPanel card = createDarkCard(20, 40, 380, 250);
        JLabel robot = createRobotIcon(280, -10, "/images/robotAdd.png");

        JLabel title = new JLabel("¡Bienvenido!");
        title.setFont(new Font("Georgia", Font.BOLD, 20));
        title.setForeground(ACCENT);
        title.setBounds(24, 24, 200, 32);

        JLabel lbl = new JLabel("Tu nombre:");
        lbl.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        lbl.setForeground(TEXT_MUTED);
        lbl.setBounds(24, 76, 200, 20);

        jtName = createDarkTextField(24, 100, 330, 40);

        jBtnAceptar = createPopupOkButton("Comenzar →", 24, 162, 150, 38);
        jBtnAceptar.addActionListener(evt -> {
            Mediador.getInstance().primerRegistro(jtName.getText());
            dialog.dispose();
        });

        card.add(title); card.add(lbl); card.add(jtName); card.add(jBtnAceptar);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }
    public void showIpPopup() {
        JDialog dialog = createBaseDialog(420, 300);
        JPanel root = new JPanel(null); root.setOpaque(false);

        JPanel card = createDarkCard(20, 40, 380, 240);
        JLabel robot = createRobotIcon(260, -10, "/images/robotAdd.png");

        JButton btnCerrar = new JButton();

        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/x1.png"));
            Image img = icon.getImage().getScaledInstance(40, 30, Image.SCALE_SMOOTH);
            btnCerrar.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            btnCerrar.setText("X");
        }

        btnCerrar.setBounds(340, 12, 25, 25);
        btnCerrar.setForeground(TEXT_MUTED);
        btnCerrar.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setFocusPainted(false);
        btnCerrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCerrar.addActionListener(e -> dialog.dispose());

        JLabel title = new JLabel("Actualizar IP");
        title.setFont(new Font("Georgia", Font.BOLD, 18));
        title.setForeground(TEXT_PRIMARY);
        title.setBounds(24, 24, 200, 30);

        JLabel lbl = new JLabel("Nueva IP:");
        lbl.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        lbl.setForeground(TEXT_MUTED);
        lbl.setBounds(24, 70, 200, 20);

        jtName = createDarkTextField(24, 94, 330, 40);

        jBtnAceptar = createPopupOkButton("Guardar", 24, 155, 120, 38);
        jBtnAceptar.addActionListener(evt -> {
            this.contactController.actualizarIp(idUsuarioActual, jtName.getText());
            dialog.dispose();
        });

        card.add(btnCerrar); card.add(title); card.add(lbl); card.add(jtName); card.add(jBtnAceptar);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }
    private void showEnviarContactoPopup() {
        JDialog dialog = createBaseDialog(420, 310);
        JPanel root = new JPanel(null); root.setOpaque(false);

        JPanel card = createDarkCard(20, 40, 380, 250);
        JLabel robot = createRobotIcon(280, -10, "/images/robotAdd.png");

        JButton btnCerrar = new JButton();
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/x1.png"));
            Image img = icon.getImage().getScaledInstance(40, 30, Image.SCALE_SMOOTH);
            btnCerrar.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            btnCerrar.setText("X");
        }

        btnCerrar.setBounds(340, 12, 25, 25);
        btnCerrar.setForeground(TEXT_MUTED);
        btnCerrar.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setBorderPainted(false);
        btnCerrar.setFocusPainted(false);
        btnCerrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCerrar.addActionListener(e -> dialog.dispose());

        JLabel title = new JLabel("Compartir Contacto");
        title.setFont(new Font("Georgia", Font.BOLD, 18));
        title.setForeground(TEXT_PRIMARY);
        title.setBounds(24, 24, 240, 30);

        JLabel lbl = new JLabel("Nombre a compartir:");
        lbl.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        lbl.setForeground(TEXT_MUTED);
        lbl.setBounds(24, 76, 220, 20);

        jtNameEnviarContacto = createDarkTextField(24, 100, 330, 40);

        jBtnEnviarContacto = createPopupOkButton("Enviar →", 24, 162, 120, 38);
        jBtnEnviarContacto.addActionListener(evt -> {
            Mediador.getInstance().enviarContacto(idUsuarioActual, jtNameEnviarContacto.getText());
            dialog.dispose();
        });

        card.add(btnCerrar); card.add(title); card.add(lbl); card.add(jtNameEnviarContacto); card.add(jBtnEnviarContacto);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }
    private void showAgregarContactoPopup() {
        JDialog dialog = createBaseDialog(340, 210);
        JPanel root = new JPanel(null); root.setOpaque(false);

        JPanel card = createDarkCard(20, 30, 300, 160);
        JLabel robot = createRobotIcon(210, -10, "/images/robotAccept.png");

        JLabel title = new JLabel("✓ Contacto agregado");
        title.setFont(new Font("Georgia", Font.BOLD, 16));
        title.setForeground(new Color(134, 239, 172));
        title.setBounds(20, 28, 220, 28);

        JButton ok = createPopupOkButton("OK", 20, 100, 90, 34);
        ok.addActionListener(e -> dialog.dispose());

        card.add(title); card.add(ok);
        root.add(robot); root.add(card);
        dialog.add(root); dialog.setVisible(true);
    }

    private void jBtnEnviarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jBtnEnviarActionPerformed
        String mensajeTxt = jtMensaje.getText().toString();
        if (mensajeTxt.isEmpty() || idUsuarioActual == null) {
            System.out.println("Entra aca");
            return;
        }

        System.out.println("Enviando 007...");
        Mediador.getInstance().enviarMensajePorChat(idUsuarioActual, mensajeTxt);
        jtMensaje.setText("");

    }//GEN-LAST:event_jBtnEnviarActionPerformed
    private void jBtnOffActionPerformed(ActionEvent evt) {
        try {
            System.out.println("Enviando 0018...");
            System.out.println("Conexion terminada");
            Message message = new FueraLinea(Mediador.getInstance().getIdMio());
            Mediador.getInstance().enviarMensajeATodos(message);
            mostrarMensajeSistema("CONEXION TERMINADA");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void jBtnNuevaConexionActionPerformed(ActionEvent evt) {
        showNuevaConexionPopup();
    }

    public void agregarContacto(Contact contact) {
        if (contact == null || contact.getId() == null) {
            return;
        }
        for (int i = 0; i < contacModel.size(); i++) {
            if (contacModel.get(i).getId().equals(contact.getId())) {
                return;
            }
        }
        contacModel.addElement(contact);
    }
    public void actualizarContacto(Contact contact) {
        for (int i = 0; i < contacModel.size(); i++) {
            Contact c = contacModel.get(i);
            if (c.getId().equals(contact.getId())) {
                c.setName(contact.getName());
                c.setIp(contact.getIp());
                contacModel.set(i, c);
                break;
            }
        }
        jContactos.repaint();
    }
    public void mostrarMensajeSistema(String texto) {
        JPanel panelSistema = new JPanel(new FlowLayout(FlowLayout.CENTER));
        panelSistema.setOpaque(false);

        JLabel lblSistema = new JLabel("⚠ " + texto);
        lblSistema.setForeground(SYSTEM_RED);
        lblSistema.setFont(new Font("Segoe UI", Font.BOLD, 11));
        lblSistema.setBorder(BorderFactory.createCompoundBorder(
                new ChatUI.RoundedBorder(10, new Color(239, 68, 68, 25), new Color(239, 68, 68, 60), 1),
                BorderFactory.createEmptyBorder(4, 12, 4, 12)
        ));

        panelSistema.add(lblSistema);
        jPanelChat.add(panelSistema);
        jPanelChat.revalidate();
        jPanelChat.repaint();
    }
    public void actualizarValores(String idUsuarioActual) {
        this.idUsuarioActual = idUsuarioActual;
    }

    public void fijarMensajeUI(String idMensaje, String texto) {
        mensajeFijadoId = idMensaje;
        mensajeFijadoTexto = texto;
        String textoCortado = texto.length() > 60 ? texto.substring(0, 57) + "…" : texto;
        lblMensajeFijado.setText(textoCortado);
        panelMensajeFijado.setVisible(true);
        panelMensajeFijado.revalidate();
        panelMensajeFijado.repaint();
    }

    private void desfijarMensaje() {
        mensajeFijadoId = null;
        mensajeFijadoTexto = null;
        panelMensajeFijado.setVisible(false);
    }

    private JLabel crearFotoPerfilyo() {
        JLabel foto = new JLabel();
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/user.png"));
            Image img = icon.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
            foto.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            foto.setText("");
        }
        return foto;
    }
    private JLabel crearFotoPerfil() {
        JLabel foto = new JLabel();
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/people.png"));
            Image img = icon.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
            foto.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            foto.setText("");
        }
        return foto;
    }


    private JPanel crearBurbuja(String texto, boolean esMio, String hora, boolean leido, String idMensaje) {
        JPanel bubble = new JPanel(new BorderLayout()) {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(getBackground());
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 18, 18);
                g2.dispose();
            }
        };
        bubble.setOpaque(false);
        bubble.setBorder(BorderFactory.createEmptyBorder(8, 14, 8, 14));
        bubble.setMaximumSize(new Dimension(320, Integer.MAX_VALUE));
        bubble.setBackground(esMio ? BG_BUBBLE_ME : BG_BUBBLE_YOU);

        JLabel lblTexto;
        String colorHex = esMio ? "#e0e7ff" : "#cbd5e1";

        if (texto.equals("Eliminaste este mensaje") || texto.equals("Se elimino este mensaje")) {
            lblTexto = new JLabel(
                    "<html><body style='max-width:230px; color:#6b7280; font-style:italic; font-family:Segoe UI;'>" + texto + "</body></html>"
            );
        } else {
            lblTexto = new JLabel(
                    "<html><body style='max-width:230px; color:" + colorHex + "; font-family:Segoe UI;'>" + texto + "</body></html>"
            );
        }

        JLabel lblHora = new JLabel(hora);
        lblHora.setFont(new Font("Segoe UI", Font.PLAIN, 9));
        lblHora.setForeground(esMio ? new Color(196, 181, 253, 180) : new Color(148, 163, 184, 180));

        JPanel panelInferior = new JPanel(new FlowLayout(FlowLayout.RIGHT, 3, 0));
        panelInferior.setOpaque(false);
        panelInferior.add(lblHora);
        lblTexto.setName(idMensaje);

        if (esMio) {
            JLabel lblCheck = new JLabel(leido ? "✔✔" : "✔");
            lblCheck.setName(idMensaje);
            lblCheck.setFont(new Font("Segoe UI", Font.PLAIN, 9));
            lblCheck.setForeground(leido ? new Color(167, 243, 208) : new Color(148, 163, 184));
            panelInferior.add(lblCheck);

            JPopupMenu popupMensaje = new JPopupMenu();
            stylePopupMenu(popupMensaje);
            JMenuItem itemEliminar = createMenuItem("🗑  Eliminar mensaje");
            if (!texto.equals("Eliminaste este mensaje")) {
                itemEliminar.addActionListener(e -> {
                    int confirm = JOptionPane.showConfirmDialog(
                            this,
                            "¿Deseas eliminar este mensaje?",
                            "Eliminar",
                            JOptionPane.YES_NO_OPTION
                    );
                    if (confirm == JOptionPane.YES_OPTION) {
                        lblTexto.setText("<html><body style='max-width:230px; color:#6b7280; font-style:italic;'>Eliminaste este mensaje</body></html>");
                        bubble.revalidate();
                        bubble.repaint();
                        this.chatsController.eliminarMensajeBD(idMensaje);
                        EliminarMensaje eliminarMensaje = new EliminarMensaje(idMensaje);
                        Mediador.getInstance().sendMessage(idUsuarioActual, eliminarMensaje);
                    }
                });
                popupMensaje.add(itemEliminar);
            }

            JMenuItem itemFijar = createMenuItem("📌  Fijar mensaje");
            itemFijar.addActionListener(e -> {
                fijarMensajeUI(idMensaje, texto);
                FijarMensaje fijarMsg = new FijarMensaje(idMensaje);
                Mediador.getInstance().sendMessage(idUsuarioActual, fijarMsg);
            });
            popupMensaje.add(itemFijar);

            bubble.addMouseListener(new MouseAdapter() {
                private void mostrarPopup(MouseEvent e) {
                    if (SwingUtilities.isRightMouseButton(e)) popupMensaje.show(bubble, e.getX(), e.getY());
                }
                @Override public void mousePressed(MouseEvent e) { mostrarPopup(e); }
                @Override public void mouseReleased(MouseEvent e) { mostrarPopup(e); }
            });


        }

        bubble.add(lblTexto, BorderLayout.CENTER);
        bubble.add(panelInferior, BorderLayout.SOUTH);
        return bubble;
    }
    private JPanel crearFilaMensaje(String texto, boolean esMio, String fechaHora, boolean leido, String idMensaje) {
        JPanel fila = new JPanel(new BorderLayout());
        fila.setOpaque(false);
        fila.setBorder(BorderFactory.createEmptyBorder(4, 12, 4, 12));
        fila.setMaximumSize(new Dimension(Integer.MAX_VALUE, Integer.MAX_VALUE));

        String soloHora = formatearSoloHora(fechaHora);
        JPanel bubble = crearBurbuja(texto, esMio, soloHora, leido, idMensaje);

        if (esMio) {
            JPanel contenedor = new JPanel(new FlowLayout(FlowLayout.RIGHT, 6, 0));
            contenedor.setOpaque(false);
            contenedor.add(bubble);
            contenedor.add(crearFotoPerfilyo());
            fila.add(contenedor, BorderLayout.EAST);
        } else {
            JPanel contenedor = new JPanel(new FlowLayout(FlowLayout.LEFT, 6, 0));
            contenedor.setOpaque(false);
            contenedor.add(crearFotoPerfil());
            contenedor.add(bubble);
            fila.add(contenedor, BorderLayout.WEST);
        }

        return fila;
    }
    private String formatearSoloHora(String fechaHora) {
        try {
            java.time.LocalDateTime dateTime =
                    java.time.LocalDateTime.parse(fechaHora, java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
            return dateTime.format(java.time.format.DateTimeFormatter.ofPattern("HH:mm"));
        } catch (Exception e) {
            return fechaHora;
        }
    }
    public void agregarMensajeUI(String texto, boolean esMio, String fechaHora, boolean leido, String idMensaje) {
        JPanel mensaje = crearFilaMensaje(texto, esMio, fechaHora, leido, idMensaje);
        jPanelChat.add(mensaje);
        jPanelChat.revalidate();
        jPanelChat.repaint();
        SwingUtilities.invokeLater(() -> {
            JScrollBar vertical = jScrollPaneChat.getVerticalScrollBar();
            vertical.setValue(vertical.getMaximum());
        });
    }
    private void limpiarChat() {
        jPanelChat.removeAll();
        jPanelChat.revalidate();
        jPanelChat.repaint();
        mensajeFijadoId = null;
        mensajeFijadoTexto = null;
        if (panelMensajeFijado != null) panelMensajeFijado.setVisible(false);
    }

    private String mensajePorFecha(String fechaHora) {
        try {
            java.time.LocalDateTime dateTime =
                    java.time.LocalDateTime.parse(
                            fechaHora,
                            java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
                    );
            return dateTime.format(
                    java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd")
            );
        } catch (Exception e) {
            return "";
        }
    }
    private void agregarSeparadorFecha(String fecha) {
        JPanel panelFecha = new JPanel(new FlowLayout(FlowLayout.CENTER));
        panelFecha.setOpaque(false);
        JLabel lblFecha = new JLabel("── " + fecha + " ──");
        lblFecha.setForeground(TEXT_MUTED);
        lblFecha.setFont(new Font("Segoe UI", Font.PLAIN, 11));
        panelFecha.add(lblFecha);
        jPanelChat.add(panelFecha);
    }
    public void actualizarChecksAzules(String idMensaje) {
        for (Component filaComp : jPanelChat.getComponents()) {
            if (!(filaComp instanceof JPanel fila)) continue;
            for (Component contenedorComp : fila.getComponents()) {
                if (!(contenedorComp instanceof JPanel contenedor)) continue;
                for (Component bubbleComp : contenedor.getComponents()) {
                    if (!(bubbleComp instanceof JPanel bubble)) continue;
                    for (Component inner : bubble.getComponents()) {
                        if (!(inner instanceof JPanel panelInferior)) continue;
                        for (Component checkComp : panelInferior.getComponents()) {
                            if (checkComp instanceof JLabel lbl && idMensaje.equals(lbl.getName())) {
                                lbl.setText("✔✔");
                                lbl.setForeground(new Color(167, 243, 208));
                                panelInferior.revalidate();
                                panelInferior.repaint();
                                return;
                            }
                        }
                    }
                }
            }
        }
    }
    public void actualizarMensajeEliminado(String idMensaje) {
        for (Component filaComp : jPanelChat.getComponents()) {
            if (!(filaComp instanceof JPanel fila)) continue;
            for (Component contenedorComp : fila.getComponents()) {
                if (!(contenedorComp instanceof JPanel contenedor)) continue;
                for (Component bubbleComp : contenedor.getComponents()) {
                    if (!(bubbleComp instanceof JPanel bubble)) continue;
                    for (Component inner : bubble.getComponents()) {
                        if (inner instanceof JLabel lbl && idMensaje.equals(lbl.getName())) {
                            Component centro = ((BorderLayout) bubble.getLayout()).getLayoutComponent(BorderLayout.CENTER);
                            if (centro instanceof JLabel lblTexto) {
                                SwingUtilities.invokeLater(() -> {
                                    lblTexto.setText("<html><body style='max-width:220px; color:gray;'><i>Se eliminó este mensaje</i></body></html>");
                                    bubble.revalidate();
                                    bubble.repaint();
                                });
                            }
                            return;
                        }
                    }
                }
            }
        }
    }
    public void actualizarEstadoContacto(String id, boolean estado) {
        for (int i = 0; i < contacModel.size(); i++) {
            Contact c = contacModel.get(i);
            if (c.getId().equals(id)) {
                c.setStateConnect(estado);
                contacModel.set(i, c);
                break;
            }
        }
        jContactos.repaint();
    }

    public void marcarContactoConMensajeNuevo(String id) {
        for (int i = 0; i < contacModel.size(); i++) {
            Contact c = contacModel.get(i);
            if (c.getId().equals(id)) {
                c.setMensajesNoLeidos(true);
                contacModel.set(i, c);
                break;
            }
        }
        jContactos.repaint();
    }
    public void marcarZumbido(String id) {
        for (int i = 0; i < contacModel.size(); i++) {
            Contact c = contacModel.get(i);
            if (c.getId().equals(id)) {
                c.setZumbido(true);
                contacModel.set(i, c);
                break;
            }
        }
        jContactos.repaint();
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChatView().setVisible(true);
//            }
//        });
//    }

//     Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jBtnEnviar;
    private JTextField jtMensaje;
    private JPanel jPanelChat;
    private JScrollPane jScrollPaneChat;
    private JButton jBtnNuevaConexion;
    private JButton jBtnOff;
    private JList<Contact> jContactos;
    private JPopupMenu jPopupMenu;
    private JMenuItem itemZumbido;
    private JMenuItem itemHello;
    private JMenuItem itemInvitacion;
    private JMenuItem itemEnviarContacto;
    private JMenuItem itemActualizarIp;
    private JButton jBtnConectar;
    private JButton jBtnAceptar;
    private JTextField jtIp;
    private JTextField jtName;
    private JTextField jtNameEnviarContacto;
    private JButton jBtnEnviarContacto;
    private JLabel lblContactoSeleccionado;
    private String mensajeFijadoId = null;
    private String mensajeFijadoTexto = null;
    private JPanel panelMensajeFijado;
    private JLabel lblMensajeFijado;

    public void onMessage(Message message) {
        if (message instanceof Aceptar) {
            System.out.println("Entra en 002 Aceptar" + '\n');
            showAcceptPopup();
        }
        if  (message instanceof Rechazar) {
            System.out.println("Entra en 003 Solicitud Rechazada" + '\n');
            showDeclinePopup();
        }
        if (message instanceof Mensaje) {
            Mensaje mensaje = (Mensaje) message;
            if (!mensaje.getIdUsuario().equals(idUsuarioActual)) {
                marcarContactoConMensajeNuevo(mensaje.getIdUsuario());
            }
            if (mensaje.getIdUsuario().equals(idUsuarioActual) && !idUsuarioActual.equals(Mediador.getInstance().getIdMio())) {
                agregarMensajeUI(mensaje.getMensaje(), false, Mediador.getInstance().obtenerHoraActual(), false, mensaje.getIdMensaje());
            }
            if (!idUsuarioActual.equals(Mediador.getInstance().getIdMio())) {
                chatsController.guardarEnBd(mensaje.getIdMensaje(), mensaje.getMensaje(), mensaje.getIdUsuario(), Mediador.getInstance().getIdMio(), Mediador.getInstance().obtenerHoraActual());
            }
            if (mensaje.getIdUsuario().equals(idUsuarioActual)) {
                ConfirmarRecibido confirmarRecibido = new ConfirmarRecibido(mensaje.getIdMensaje());
                System.out.println("Enviando 008...");
                Mediador.getInstance().sendMessage(idUsuarioActual, confirmarRecibido);
                Mediador.getInstance().actualizarLeidoBd(mensaje.getIdMensaje());
            }
            if (mensaje.getMensaje().toLowerCase().equals("chau")){
                System.out.println("Enviando 0018...");
                System.out.println("Conexion terminada");
                Message message1 = new FueraLinea(Mediador.getInstance().getIdMio());
                Mediador.getInstance().enviarChau(message1, mensaje.getIdUsuario());
                mostrarMensajeSistema("CONEXION TERMINADA");
                actualizarEstadoContacto(mensaje.getIdUsuario(), false);
            }
        }
        if (message instanceof Hello) {
            Hello hello = (Hello) message;
            System.out.println("Se recibio el Hello de: " + hello.getIdUsuario() + '\n');
        }
        if (message instanceof AceptarHello) {
            System.out.println("Hello Aceptado");
        }
        if (message instanceof RechazarHello) {
            System.out.println("Hello Rechazado");
        }
        if (message instanceof ConfirmarRecibido) {
            SwingUtilities.invokeLater(() ->
                    actualizarChecksAzules(((ConfirmarRecibido) message).getIdMensaje())
            );

        }
        if (message instanceof FueraLinea) {
            System.out.println("Conexión terminada por cliente");
            showOffPopup();
            mostrarMensajeSistema("CONEXION TERMINADA");
            actualizarEstadoContacto(idUsuarioActual, false);
        }

        if (message instanceof EnviarContacto) {
            System.out.println("contacto agregado");
            EnviarContacto enviarContacto = (EnviarContacto) message;
            Contact nuevo = new Contact(
                    enviarContacto.getIdUsuario(),
                    enviarContacto.getNombreCliente(),
                    enviarContacto.getIp(),
                    false,
                    false,
                    false
            );

            SwingUtilities.invokeLater(() -> {
                agregarContacto(nuevo);
                jContactos.revalidate();
                jContactos.repaint();
            });
            showAgregarContactoPopup();
        }
        if (message instanceof EliminarMensaje) {
            EliminarMensaje eliminarMensaje = (EliminarMensaje) message;
            this.chatsController.mensajeeliminadoPorCLiente(eliminarMensaje.getIdMensaje());
            actualizarMensajeEliminado(eliminarMensaje.getIdMensaje());
        }

     }

    @Override
    public void onloadContacts(List<Contact> contacts) {
        try {
            if (contacts.isEmpty())
                System.out.println("BD vacia");
            contacModel.clear();
            contacModel.addAll(contacts);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void onloadMessages(List<Chats> chats) {
        limpiarChat();
        String ultimaFecha = "";

        for (Chats c : chats) {
//            String fechaActual = mensajePorFecha(c.getHora());

//            if (!fechaActual.equals(ultimaFecha)) {
//                agregarSeparadorFecha(fechaActual);
//                ultimaFecha = fechaActual;
//            }

            boolean esMio = c.getIdEmisor().equals(Mediador.getInstance().getIdMio());
            boolean leido = c.getLeido().equals("1");

            agregarMensajeUI(
                    c.getMensajeTxt(),
                    esMio,
                    c.getHora(),
                    leido,
                    c.getIdMensaje()
            );
            if (!esMio && !leido) {
                System.out.println("Enviando 008...");
                ConfirmarRecibido confirmarRecibido = new ConfirmarRecibido(c.getIdMensaje());
                Mediador.getInstance().sendMessage(c.getIdEmisor(), confirmarRecibido);
                Mediador.getInstance().actualizarLeidoBd(c.getIdMensaje());
            }
        }
    }
    static class RoundedBorder extends AbstractBorder {
        private final int radius;
        private final Color fill;
        private final Color stroke;
        private final int thickness;

        RoundedBorder(int radius, Color fill, Color stroke, int thickness) {
            this.radius = radius; this.fill = fill; this.stroke = stroke; this.thickness = thickness;
        }

        @Override
        public void paintBorder(Component c, Graphics g, int x, int y, int w, int h) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(fill);
            g2.fillRoundRect(x, y, w - 1, h - 1, radius * 2, radius * 2);
            g2.setColor(stroke);
            g2.setStroke(new BasicStroke(thickness));
            g2.drawRoundRect(x, y, w - 1, h - 1, radius * 2, radius * 2);
            g2.dispose();
        }

        @Override
        public Insets getBorderInsets(Component c) { return new Insets(thickness, thickness, thickness, thickness); }
        @Override
        public boolean isBorderOpaque() { return false; }
    }
    // End of variables declaration//GEN-END:variables
}