/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upb.chatupb_v2;

import edu.upb.chatupb_v2.bl.message.*;
import edu.upb.chatupb_v2.bl.server.Mediador;
import edu.upb.chatupb_v2.bl.server.SocketClient;
import edu.upb.chatupb_v2.bl.server.SocketListener;

import javax.swing.*;

/**
 *
 * @author rlaredo
 */
public class ChatView extends JFrame implements SocketListener {
    SocketClient client;
    private String idUsuarioActivo;
    private final String idMio = "8179864";
    private final String nombre = "Irene";

//    ChatServer chatServer;

    /**
     * Creates new form ChatUI
     */
    public ChatView() {
        initComponents();
//        try{
//            chatServer = new ChatServer();
//            chatServer.addListener(this);
//            chatServer.start();
//        }catch(Exception e){
//            e.printStackTrace();
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnEnviar = new JButton();
        jtMensaje = new JTextField();
        jTextPaneChat = new JTextPane();
        jTextPaneChat.setEditable(false);

        jScrollPaneChat = new JScrollPane();
        jScrollPaneChat.setViewportView(jTextPaneChat);

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);


        jBtnEnviar.setText("Enviar");
        jBtnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEnviarActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPaneChat, GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jtMensaje)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jBtnEnviar)))
                                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPaneChat, GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtMensaje, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jBtnEnviar))
                                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEnviarActionPerformed
        // TODO add your handling code here:
        if (client != null) {
            try {
                System.out.println("Enviando 007...");
                String mensajeTxt = jtMensaje.getText().toString();
                if (idUsuarioActivo == null) {
                    JOptionPane.showMessageDialog(this, "No hay usuario conectado");
                    return;
                }
                System.out.println("id usuario: " + idUsuarioActivo);
                Message message = new Mensaje(idMio, "012", mensajeTxt);
                Mediador.getInstance().sendMessage(idUsuarioActivo, message);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jBtnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatView().setVisible(true);
            }
        });
    }

//     Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jBtnEnviar;
    private JTextField jtMensaje;
    private JTextPane jTextPaneChat;
    private JScrollPane jScrollPaneChat;

    @Override
    public void onMessage(SocketClient socketClient, Message message) {
        if (message instanceof Invitacion) {
            System.out.println("Llego la invitacion");

            Invitacion invitacion = (Invitacion) message;
            int respuesta = JOptionPane.showConfirmDialog(
                    this,
                    "LLego la invitacion: " + invitacion
                    , "Invitacion",
                    JOptionPane.YES_NO_OPTION); // esto le llega al CLiente

            if (respuesta == JOptionPane.YES_OPTION) {
                System.out.println("id invitacion: " + invitacion.getIdUsuario());
                Mediador.getInstance().addClient(invitacion.getIdUsuario(), socketClient);
                Message aceptar = new Aceptar(idMio, nombre);
                Mediador.getInstance().sendMessage(invitacion.getIdUsuario(), aceptar);
                idUsuarioActivo = invitacion.getIdUsuario();
                client = socketClient;
            }
            if (respuesta == JOptionPane.NO_OPTION) {
                try {
                    Message rechazar = new Rechazar();
                    socketClient.send(rechazar);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
        if (message instanceof Aceptar) {
            Aceptar aceptar = (Aceptar) message;
            Mediador.getInstance().addClient(aceptar.getIdUsuario(), socketClient);
            idUsuarioActivo = aceptar.getIdUsuario();
        }
        if (message instanceof Mensaje) {
            Mensaje mensaje = (Mensaje) message;
            System.out.println("Llegó el mensaje: " + mensaje);
        }
    }
    // End of variables declaration//GEN-END:variables
}
