/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upb.chatupb_v2;

import edu.upb.chatupb_v2.bl.message.*;
import edu.upb.chatupb_v2.bl.server.Mediador;
import edu.upb.chatupb_v2.bl.server.SocketClient;
import edu.upb.chatupb_v2.bl.server.SocketListener;

import javax.swing.*;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author rlaredo
 */
public class ChatView extends JFrame implements SocketListener {
    SocketClient client;
    private String idUsuarioActivo;
    private final String idMio = "8179864";
    private final String nombre = "Irene";

//    ChatServer chatServer;

    /**
     * Creates new form ChatUI
     */
    public ChatView(SocketClient client, String idUsuarioActivo) {
        this.client = client;
        this.idUsuarioActivo = idUsuarioActivo;

        initComponents();

        client.addListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnEnviar = new JButton();
        jtMensaje = new JTextField();
        jTextPaneChat = new JTextPane();
        jTextPaneChat.setEditable(false);

        jScrollPaneChat = new JScrollPane();
        jScrollPaneChat.setViewportView(jTextPaneChat);

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);


        jBtnEnviar.setText("Enviar");
        jBtnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEnviarActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPaneChat, GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jtMensaje)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jBtnEnviar)))
                                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPaneChat, GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtMensaje, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jBtnEnviar))
                                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEnviarActionPerformed
        // TODO add your handling code here:
        if (idUsuarioActivo != null) {
            try {
                System.out.println("Enviando 007...");
                String mensajeTxt = jtMensaje.getText().toString();
                if (idUsuarioActivo == null) {
                    JOptionPane.showMessageDialog(this, "No hay usuario conectado");
                    return;
                }
                agregarMensaje(mensajeTxt, true);
                Message message = new Mensaje(idMio, "012", mensajeTxt);
                Mediador.getInstance().sendMessage(idUsuarioActivo, message);
                jtMensaje.setText("");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jBtnEnviarActionPerformed

    private void agregarMensaje(String texto, boolean esMio) {
        StyledDocument doc = jTextPaneChat.getStyledDocument();
        SimpleAttributeSet attrs = new SimpleAttributeSet();

        if (esMio) {
            StyleConstants.setAlignment(attrs, StyleConstants.ALIGN_RIGHT);
            StyleConstants.setForeground(attrs, java.awt.Color.BLUE);
        } else {
            StyleConstants.setAlignment(attrs, StyleConstants.ALIGN_LEFT);
            StyleConstants.setForeground(attrs, java.awt.Color.BLACK);
        }

        try {
            int len = doc.getLength();
            doc.insertString(len, texto + "\n", attrs);
            doc.setParagraphAttributes(len, texto.length(), attrs, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChatView().setVisible(true);
//            }
//        });
//    }

//     Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jBtnEnviar;
    private JTextField jtMensaje;
    private JTextPane jTextPaneChat;
    private JScrollPane jScrollPaneChat;

    @Override
    public void onMessage(SocketClient socketClient, Message message) {
        if (message instanceof Mensaje) {
            Mensaje mensaje = (Mensaje) message;
            agregarMensaje(mensaje.getMensaje(), false);
            System.out.println("Llegó el mensaje: " + mensaje);
        }
    }
    // End of variables declaration//GEN-END:variables
}
